// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ErrorCodeBadRequest      ErrorCode = "bad_request"
	ErrorCodeForbidden       ErrorCode = "forbidden"
	ErrorCodeInternal        ErrorCode = "internal"
	ErrorCodeNotFound        ErrorCode = "not_found"
	ErrorCodeTooManyRequests ErrorCode = "too_many_requests"
	ErrorCodeUnauthenticated ErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeBadRequest:
		return true
	case ErrorCodeForbidden:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeTooManyRequests:
		return true
	case ErrorCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for PrincipalKind.
const (
	Human   PrincipalKind = "human"
	Machine PrincipalKind = "machine"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case Human:
		return true
	case Machine:
		return true
	default:
		return false
	}
}

// Assurance How **this session** authenticated — not what the account owns.
// Authorization of an MFA-mandatory capability consults this record at
// the same chokepoint as `authorize()`, in the same transaction,
// uncached.
type Assurance struct {
	// AuthenticatedAt RFC 3339 UTC, microsecond precision.
	AuthenticatedAt Timestamp `json:"authenticated_at"`

	// CeremonyId The factor ceremony this session's assurance came from, where one
	// occurred. `null` for a single-factor password login.
	CeremonyId *string `json:"ceremony_id,omitempty"`

	// Factors The factor classes actually presented in this session.
	Factors []FactorClass `json:"factors"`

	// Method OPEN enum — `oidc:<issuer>` values are instance-specific by construction.
	Method AuthMethod `json:"method"`
}

// AuthMethod OPEN enum — `oidc:<issuer>` values are instance-specific by construction.
type AuthMethod = string

// CreateOrgRequest defines model for CreateOrgRequest.
type CreateOrgRequest struct {
	Active *bool `json:"active,omitempty"`

	// Metadata Free-form operator metadata. `null` and absent both mean "no
	// metadata"; the round-trip of absent/null/value is fixture-pinned
	// through both the Go and the TypeScript consumer.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Closed set — never grows. Clients branch on this, not on prose.
		Code ErrorCode `json:"code"`

		// Detail Present only on `bad_request`, where it names the offending
		// request member. `null` and absent are equivalent; every other
		// error code omits the member entirely.
		Detail *string `json:"detail,omitempty"`

		// Message Fixed per code. Never derived from the request, so two
		// refusals of the same class are byte-identical.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorCode Closed set — never grows. Clients branch on this, not on prose.
type ErrorCode string

// EstablishCredentialRequest defines model for EstablishCredentialRequest.
type EstablishCredentialRequest struct {
	// Authority The single-use credential-establishment authority, exactly as
	// delivered. Never logged, never audited, never echoed.
	Authority string `json:"authority"`

	// Password The initial credential. Minimum length 12, no composition rules,
	// no forced rotation (NIST SP 800-63B shape); checked against a
	// bundled common-password list at set time only, never at login.
	Password string `json:"password"`
}

// FactorClass OPEN enum — new factor classes are additive.
type FactorClass = string

// ID A prefixed UUIDv7, e.g. `org_0198…`.
type ID = string

// LocalLoginRequest defines model for LocalLoginRequest.
type LocalLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Principal Principal `json:"principal"`
	Session   Session   `json:"session"`

	// SessionToken The bearer value, returned exactly once. A replayable credential:
	// cookie attributes constrain browsers, not an attacker holding the
	// value, which is why lifetimes are short and revocation is a
	// delete.
	SessionToken string `json:"session_token"`
}

// Meta An exact closed allowlist. `additionalProperties: false` is the
// allowlist's teeth: a field added here is a visible spec change, not a
// quiet leak of instance configuration to unauthenticated callers.
type Meta struct {
	// ApiRevision This server's API revision. A client refuses an operation whose
	// `x-wenv-min-revision` exceeds it, naming the server version — a
	// loud refusal, never a silent misbehave.
	ApiRevision int `json:"api_revision"`

	// ProtocolCapabilities Which authentication protocol flows this instance serves. `login`
	// needs this before any session exists.
	ProtocolCapabilities []ProtocolCapability `json:"protocol_capabilities"`

	// ServerVersion The build's version string; `dev` for unreleased builds.
	ServerVersion string `json:"server_version"`
}

// Org defines model for Org.
type Org struct {
	Active bool `json:"active"`

	// CreatedAt RFC 3339 UTC, microsecond precision.
	CreatedAt Timestamp `json:"created_at"`

	// Id A prefixed UUIDv7, e.g. `org_0198…`.
	Id       ID                      `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
}

// OrgList defines model for OrgList.
type OrgList struct {
	// Count Total rows matching, which for an unpaged list equals `items` length.
	Count int   `json:"count"`
	Items []Org `json:"items"`
}

// Principal defines model for Principal.
type Principal struct {
	// DisplayName For display only. Never a linking key, at any point, for any provider.
	DisplayName *string `json:"display_name,omitempty"`

	// Id A prefixed UUIDv7, e.g. `org_0198…`.
	Id ID `json:"id"`

	// Kind Closed set — the human/machine distinction is structural in audit attribution.
	Kind PrincipalKind `json:"kind"`
}

// PrincipalKind Closed set — the human/machine distinction is structural in audit attribution.
type PrincipalKind string

// ProtocolCapability OPEN enum: an instance may advertise a flow this client has never
// heard of, and every generated consumer must preserve and tolerate the
// unknown value rather than reject the response.
type ProtocolCapability = string

// Session defines model for Session.
type Session struct {
	// AbsoluteExpiresAt RFC 3339 UTC, microsecond precision.
	AbsoluteExpiresAt Timestamp `json:"absolute_expires_at"`

	// Artifact OPEN enum: human sessions are per-client-class artifacts and new
	// classes are additive. A browser cookie's attributes protect nothing on
	// a non-browser client, and conflating the two hides which artifact was
	// actually used.
	Artifact SessionArtifact `json:"artifact"`

	// Assurance How **this session** authenticated — not what the account owns.
	// Authorization of an MFA-mandatory capability consults this record at
	// the same chokepoint as `authorize()`, in the same transaction,
	// uncached.
	Assurance Assurance `json:"assurance"`

	// CreatedAt RFC 3339 UTC, microsecond precision.
	CreatedAt Timestamp `json:"created_at"`

	// Id A prefixed UUIDv7, e.g. `org_0198…`.
	Id ID `json:"id"`

	// IdleExpiresAt RFC 3339 UTC, microsecond precision.
	IdleExpiresAt Timestamp `json:"idle_expires_at"`
}

// SessionArtifact OPEN enum: human sessions are per-client-class artifacts and new
// classes are additive. A browser cookie's attributes protect nothing on
// a non-browser client, and conflating the two hides which artifact was
// actually used.
type SessionArtifact = string

// Timestamp RFC 3339 UTC, microsecond precision.
type Timestamp = time.Time

// WhoAmI defines model for WhoAmI.
type WhoAmI struct {
	Principal Principal `json:"principal"`
	Session   Session   `json:"session"`
}

// OrgID A prefixed UUIDv7, e.g. `org_0198…`.
type OrgID = ID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// EstablishCredentialJSONRequestBody defines body for EstablishCredential for application/json ContentType.
type EstablishCredentialJSONRequestBody = EstablishCredentialRequest

// LocalLoginJSONRequestBody defines body for LocalLogin for application/json ContentType.
type LocalLoginJSONRequestBody = LocalLoginRequest

// CreateOrgJSONRequestBody defines body for CreateOrg for application/json ContentType.
type CreateOrgJSONRequestBody = CreateOrgRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// EstablishCredential Consume a credential-establishment authority and set an initial credential.
	// (POST /api/v1/auth/credential/establish)
	EstablishCredential(w http.ResponseWriter, r *http.Request)
	// LocalLogin Terminal-native local login; mints a CLI session artifact.
	// (POST /api/v1/auth/local/login)
	LocalLogin(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the presented session.
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Whoami Describe the presented session.
	// (GET /api/v1/auth/whoami)
	Whoami(w http.ResponseWriter, r *http.Request)
	// GetMeta Instance discovery, unauthenticated.
	// (GET /api/v1/meta)
	GetMeta(w http.ResponseWriter, r *http.Request)
	// ListOrgs List organisations.
	// (GET /api/v1/orgs)
	ListOrgs(w http.ResponseWriter, r *http.Request)
	// CreateOrg Create an organisation.
	// (POST /api/v1/orgs)
	CreateOrg(w http.ResponseWriter, r *http.Request)
	// GetOrg Read one organisation.
	// (GET /api/v1/orgs/{org})
	GetOrg(w http.ResponseWriter, r *http.Request, org OrgID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// EstablishCredential Consume a credential-establishment authority and set an initial credential.
// (POST /api/v1/auth/credential/establish)
func (_ Unimplemented) EstablishCredential(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LocalLogin Terminal-native local login; mints a CLI session artifact.
// (POST /api/v1/auth/local/login)
func (_ Unimplemented) LocalLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the presented session.
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Whoami Describe the presented session.
// (GET /api/v1/auth/whoami)
func (_ Unimplemented) Whoami(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMeta Instance discovery, unauthenticated.
// (GET /api/v1/meta)
func (_ Unimplemented) GetMeta(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListOrgs List organisations.
// (GET /api/v1/orgs)
func (_ Unimplemented) ListOrgs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrg Create an organisation.
// (POST /api/v1/orgs)
func (_ Unimplemented) CreateOrg(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetOrg Read one organisation.
// (GET /api/v1/orgs/{org})
func (_ Unimplemented) GetOrg(w http.ResponseWriter, r *http.Request, org OrgID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// EstablishCredential operation middleware
func (siw *ServerInterfaceWrapper) EstablishCredential(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EstablishCredential(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LocalLogin operation middleware
func (siw *ServerInterfaceWrapper) LocalLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LocalLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Whoami operation middleware
func (siw *ServerInterfaceWrapper) Whoami(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Whoami(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeta operation middleware
func (siw *ServerInterfaceWrapper) GetMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrgs operation middleware
func (siw *ServerInterfaceWrapper) ListOrgs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrg operation middleware
func (siw *ServerInterfaceWrapper) CreateOrg(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrg(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrg operation middleware
func (siw *ServerInterfaceWrapper) GetOrg(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org" -------------
	var org OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org", chi.URLParam(r, "org"), &org, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrg(w, r, org)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/meta", wrapper.GetMeta)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/credential/establish", wrapper.EstablishCredential)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/local/login", wrapper.LocalLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/whoami", wrapper.Whoami)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orgs", wrapper.ListOrgs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/orgs", wrapper.CreateOrg)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orgs/{org}", wrapper.GetOrg)
	})

	return r
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthenticatedJSONResponse Error

type EstablishCredentialRequestObject struct {
	Body *EstablishCredentialJSONRequestBody
}

type EstablishCredentialResponseObject interface {
	VisitEstablishCredentialResponse(w http.ResponseWriter) error
}

type EstablishCredential204Response struct {
}

func (response EstablishCredential204Response) VisitEstablishCredentialResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EstablishCredential400JSONResponse struct{ BadRequestJSONResponse }

func (response EstablishCredential400JSONResponse) VisitEstablishCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EstablishCredential401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response EstablishCredential401JSONResponse) VisitEstablishCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EstablishCredential429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response EstablishCredential429JSONResponse) VisitEstablishCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type EstablishCredential500JSONResponse struct{ InternalJSONResponse }

func (response EstablishCredential500JSONResponse) VisitEstablishCredentialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLoginRequestObject struct {
	Body *LocalLoginJSONRequestBody
}

type LocalLoginResponseObject interface {
	VisitLocalLoginResponse(w http.ResponseWriter) error
}

type LocalLogin200JSONResponse LoginResult

func (response LocalLogin200JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response LocalLogin400JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response LocalLogin401JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response LocalLogin429JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin500JSONResponse struct{ InternalJSONResponse }

func (response LocalLogin500JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Logout429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Logout429JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Logout500JSONResponse struct{ InternalJSONResponse }

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type WhoamiRequestObject struct {
}

type WhoamiResponseObject interface {
	VisitWhoamiResponse(w http.ResponseWriter) error
}

type Whoami200JSONResponse WhoAmI

func (response Whoami200JSONResponse) VisitWhoamiResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Whoami401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response Whoami401JSONResponse) VisitWhoamiResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Whoami429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response Whoami429JSONResponse) VisitWhoamiResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Whoami500JSONResponse struct{ InternalJSONResponse }

func (response Whoami500JSONResponse) VisitWhoamiResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetaRequestObject struct {
}

type GetMetaResponseObject interface {
	VisitGetMetaResponse(w http.ResponseWriter) error
}

type GetMeta200JSONResponse Meta

func (response GetMeta200JSONResponse) VisitGetMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeta429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetMeta429JSONResponse) VisitGetMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeta500JSONResponse struct{ InternalJSONResponse }

func (response GetMeta500JSONResponse) VisitGetMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgsRequestObject struct {
}

type ListOrgsResponseObject interface {
	VisitListOrgsResponse(w http.ResponseWriter) error
}

type ListOrgs200JSONResponse OrgList

func (response ListOrgs200JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgs401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response ListOrgs401JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgs403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListOrgs403JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgs429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ListOrgs429JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgs500JSONResponse struct{ InternalJSONResponse }

func (response ListOrgs500JSONResponse) VisitListOrgsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgRequestObject struct {
	Body *CreateOrgJSONRequestBody
}

type CreateOrgResponseObject interface {
	VisitCreateOrgResponse(w http.ResponseWriter) error
}

type CreateOrg201JSONResponse Org

func (response CreateOrg201JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOrg400JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response CreateOrg401JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateOrg403JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateOrg429JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrg500JSONResponse struct{ InternalJSONResponse }

func (response CreateOrg500JSONResponse) VisitCreateOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrgRequestObject struct {
	Org OrgID `json:"org"`
}

type GetOrgResponseObject interface {
	VisitGetOrgResponse(w http.ResponseWriter) error
}

type GetOrg200JSONResponse Org

func (response GetOrg200JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetOrg401JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetOrg403JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrg404JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetOrg429JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrg500JSONResponse struct{ InternalJSONResponse }

func (response GetOrg500JSONResponse) VisitGetOrgResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// EstablishCredential Consume a credential-establishment authority and set an initial credential.
	// (POST /api/v1/auth/credential/establish)
	EstablishCredential(ctx context.Context, request EstablishCredentialRequestObject) (EstablishCredentialResponseObject, error)
	// LocalLogin Terminal-native local login; mints a CLI session artifact.
	// (POST /api/v1/auth/local/login)
	LocalLogin(ctx context.Context, request LocalLoginRequestObject) (LocalLoginResponseObject, error)
	// Logout Revoke the presented session.
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Whoami Describe the presented session.
	// (GET /api/v1/auth/whoami)
	Whoami(ctx context.Context, request WhoamiRequestObject) (WhoamiResponseObject, error)
	// GetMeta Instance discovery, unauthenticated.
	// (GET /api/v1/meta)
	GetMeta(ctx context.Context, request GetMetaRequestObject) (GetMetaResponseObject, error)
	// ListOrgs List organisations.
	// (GET /api/v1/orgs)
	ListOrgs(ctx context.Context, request ListOrgsRequestObject) (ListOrgsResponseObject, error)
	// CreateOrg Create an organisation.
	// (POST /api/v1/orgs)
	CreateOrg(ctx context.Context, request CreateOrgRequestObject) (CreateOrgResponseObject, error)
	// GetOrg Read one organisation.
	// (GET /api/v1/orgs/{org})
	GetOrg(ctx context.Context, request GetOrgRequestObject) (GetOrgResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// EstablishCredential operation middleware
func (sh *strictHandler) EstablishCredential(w http.ResponseWriter, r *http.Request) {
	var request EstablishCredentialRequestObject

	var body EstablishCredentialJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EstablishCredential(ctx, request.(EstablishCredentialRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EstablishCredential")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EstablishCredentialResponseObject); ok {
		if err := validResponse.VisitEstablishCredentialResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LocalLogin operation middleware
func (sh *strictHandler) LocalLogin(w http.ResponseWriter, r *http.Request) {
	var request LocalLoginRequestObject

	var body LocalLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LocalLogin(ctx, request.(LocalLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LocalLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LocalLoginResponseObject); ok {
		if err := validResponse.VisitLocalLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Whoami operation middleware
func (sh *strictHandler) Whoami(w http.ResponseWriter, r *http.Request) {
	var request WhoamiRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Whoami(ctx, request.(WhoamiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Whoami")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WhoamiResponseObject); ok {
		if err := validResponse.VisitWhoamiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMeta operation middleware
func (sh *strictHandler) GetMeta(w http.ResponseWriter, r *http.Request) {
	var request GetMetaRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeta(ctx, request.(GetMetaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeta")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetaResponseObject); ok {
		if err := validResponse.VisitGetMetaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrgs operation middleware
func (sh *strictHandler) ListOrgs(w http.ResponseWriter, r *http.Request) {
	var request ListOrgsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrgs(ctx, request.(ListOrgsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrgs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrgsResponseObject); ok {
		if err := validResponse.VisitListOrgsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrg operation middleware
func (sh *strictHandler) CreateOrg(w http.ResponseWriter, r *http.Request) {
	var request CreateOrgRequestObject

	var body CreateOrgJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrg(ctx, request.(CreateOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrg")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrgResponseObject); ok {
		if err := validResponse.VisitCreateOrgResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrg operation middleware
func (sh *strictHandler) GetOrg(w http.ResponseWriter, r *http.Request, org OrgID) {
	var request GetOrgRequestObject

	request.Org = org

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrg(ctx, request.(GetOrgRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrg")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrgResponseObject); ok {
		if err := validResponse.VisitGetOrgResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
