// Code generated by internal/scanning/gen. DO NOT EDIT.

package scanning

// snapshotVersion binds the gitleaks pin and the allowlist digest.
const snapshotVersion = "gitleaks/v8.19.0+23f3bf389bd0"

// Vendoring record (ADR §3): provenance pinned executably.
const (
	gitleaksUpstream    = "github.com/gitleaks/gitleaks"
	gitleaksTag         = "v8.19.0"
	gitleaksCommit      = "44ad62e0b103f7907c4b3dd494aca64e4fefd94f"
	gitleaksSourcePath  = "config/gitleaks.toml"
	vendorTOMLSHA256    = "f0530f72a3962c6b824d7c03714a896b3e5e609d6a2f3bf11be97b6d715e1372"
	vendorLicenseSHA256 = "e3884b252b3bfc045e55be43a34d1e80da070bc6f804ac95bf4660e97d62ebc6"
)

// hikRuleID and hikRuleRegex are the single source for the Hikyo-owned
// rule's RE2 candidate stage; hik.go compiles hikRuleRegex and adds the
// procedural CRC stage.
const hikRuleID = "hikyo-artifact"
const hikRuleRegex = "hik_1_([a-z]{2,4})_[0-9A-Za-z]{7,}"

// generatedRules is the compiled-rule table, sorted by id. Each carries a
// generated keyword-coverage proof and semantic digest.
var generatedRules = []genRule{
	{id: "aws-access-token", regex: "(?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z0-9]{16}", keywords: []string{"akia", "asia", "abia", "acca"}, coverage: keywordCoverageIncomplete, specialFold: nil, digest: "244b38c5b788cfe1a8a23260c76aa9a709bcbb9d45660d372694ddce96f90888"},
	{id: "github-app-token", regex: "(?:ghu|ghs)_[0-9a-zA-Z]{36}", keywords: []string{"ghu_", "ghs_"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "e69432bd10c0592ed5bde26f8a9daec316077711fdc763144a94b39c971e6bd8"},
	{id: "github-fine-grained-pat", regex: "github_pat_[0-9a-zA-Z_]{82}", keywords: []string{"github_pat_"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "02ade5f511a904d247c56c89dd42fdf31263586127ec4d356c4d68b4adb710d8"},
	{id: "github-oauth", regex: "gho_[0-9a-zA-Z]{36}", keywords: []string{"gho_"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "6a2df4466b276ffe09c23b436ef302e7e9bece132926dc8f1be000ecb3f02639"},
	{id: "github-pat", regex: "ghp_[0-9a-zA-Z]{36}", keywords: []string{"ghp_"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "45c88e02c086446501a0c30fb78ff7e8bf2418c0dbc29cdfc9a2e6a5f610a1a3"},
	{id: "gitlab-pat", regex: "glpat-[0-9a-zA-Z\\-\\_]{20}", keywords: []string{"glpat-"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "35863ec115aee6194cd080899dee45d6c42b82281617e186a3a0afd8148703b8"},
	{id: "hikyo-artifact", regex: "hik_1_([a-z]{2,4})_[0-9A-Za-z]{7,}", keywords: []string{"hik_"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "be91301de568fa53ac89555e7d2adf208fe70bee85fc7e43d37b3a7e95895e10"},
	{id: "private-key", regex: "(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]*KEY(?: BLOCK)?----", keywords: []string{"-----begin"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "d6709fe36be8da599371568f820c37f5dfb10dfc7fb2ee8874301598393af2aa"},
	{id: "slack-bot-token", regex: "(xoxb-[0-9]{10,13}\\-[0-9]{10,13}[a-zA-Z0-9-]*)", keywords: []string{"xoxb"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "75e778189b5d38db5a219e4b700fd7e6c5068f9a6a429e04db6606a1155f55f0"},
	{id: "slack-user-token", regex: "xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}", keywords: []string{"xoxp-", "xoxe-"}, coverage: keywordCoverageComplete, specialFold: nil, digest: "cfe423d37c4eda40bdaa1f9d1d7bea915e6b1261dbe19d452d83695ec384f2ad"},
	{id: "stripe-access-token", regex: "(?i)\\b((sk|rk)_(test|live|prod)_[0-9a-z]{10,99})(?:['|\\\"|\\n|\\r|\\s|\\x60|;]|$)", keywords: []string{"sk_test", "sk_live", "sk_prod", "rk_test", "rk_live", "rk_prod"}, coverage: keywordCoverageFoldIncomplete, specialFold: []string{"ſ", "K"}, digest: "0831b29fec0d7d6d720fc836468cb896306e994103c416b4832c94b98f37f441"},
}

// generatedManifest lists the vendored rule ids compiled in, sorted. A test
// asserts it equals the committed allowlist exactly (the hik_ rule is not a
// gitleaks rule and is tracked separately).
var generatedManifest = []string{"aws-access-token", "github-app-token", "github-fine-grained-pat", "github-oauth", "github-pat", "gitlab-pat", "private-key", "slack-bot-token", "slack-user-token", "stripe-access-token"}
