// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditUnsettledThreshold = `-- name: AuditUnsettledThreshold :one

SELECT (pg_snapshot_xmin(pg_current_snapshot())::text::bigint) AS threshold
`

// Paging is bounded by the SETTLED-SEQ bound: the lowest seq whose
// transaction has not finished. Every row below it is settled, so a cursor
// can never step past a row that commits later - seq is allocated before
// commit on this engine, so that is a real omission, not a reordering. The
// unsettled threshold is the snapshot xmin (the lowest still-running xid);
// rows at or above it may or may not commit, so the bound stops there and a
// later export picks them up. An export holds one bound for all its pages,
// which also makes it terminate instead of chasing live writes.
// wenv:instance-scoped
func (q *Queries) AuditUnsettledThreshold(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, auditUnsettledThreshold)
	var threshold int64
	err := row.Scan(&threshold)
	return threshold, err
}

const insertInstanceAuditEvent = `-- name: InsertInstanceAuditEvent :exec
INSERT INTO audit_instance_events (
    id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18
)
`

type InsertInstanceAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

func (q *Queries) InsertInstanceAuditEvent(ctx context.Context, arg InsertInstanceAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertInstanceAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.RecordedAt,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec

INSERT INTO audit_tenant_events (
    id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22
)
`

type InsertTenantAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ScopeClass        string
	ChainOrgID        string
	ProjectID         pgtype.Text
	EnvID             pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

// Audit trails (#45): the application layer holds INSERT and SELECT only on
// both audit tables - the append-only CI invariant scans this file. The
// reserved chain_* parameters are bound by the store's binding layer (and,
// for the denial writer, by the authorization package's enumerated surface)
// from resolved chains only - never from caller arguments.
//
// Page order is seq (allocation order); the cursor is `seq > $n`. On this
// engine seq is allocation-ordered, not a commit-order total (stated in the
// migration and the ADR).
func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.RecordedAt,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ScopeClass,
		arg.ChainOrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const pageInstanceAudit = `-- name: PageInstanceAudit :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_instance_events
WHERE seq > $1 AND seq < $2
    AND recorded_at >= $3 AND recorded_at <= $4
ORDER BY seq LIMIT $5
`

type PageInstanceAuditParams struct {
	AfterSeq     int64
	SettledBelow int64
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	PageLimit    int32
}

func (q *Queries) PageInstanceAudit(ctx context.Context, arg PageInstanceAuditParams) ([]AuditInstanceEvent, error) {
	rows, err := q.db.Query(ctx, pageInstanceAudit,
		arg.AfterSeq,
		arg.SettledBelow,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditInstanceEvent
	for rows.Next() {
		var i AuditInstanceEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditEnv = `-- name: PageTenantAuditEnv :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND env_id = $3 AND seq > $4 AND seq < $5
    AND recorded_at >= $6 AND recorded_at <= $7
ORDER BY seq LIMIT $8
`

type PageTenantAuditEnvParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	ChainEnvID     pgtype.Text
	AfterSeq       int64
	SettledBelow   int64
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditEnv(ctx context.Context, arg PageTenantAuditEnvParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditEnv,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.AfterSeq,
		arg.SettledBelow,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditOrg = `-- name: PageTenantAuditOrg :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = $1 AND seq > $2 AND seq < $3
    AND recorded_at >= $4 AND recorded_at <= $5
ORDER BY seq LIMIT $6
`

type PageTenantAuditOrgParams struct {
	ChainOrgID   string
	AfterSeq     int64
	SettledBelow int64
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	PageLimit    int32
}

func (q *Queries) PageTenantAuditOrg(ctx context.Context, arg PageTenantAuditOrgParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditOrg,
		arg.ChainOrgID,
		arg.AfterSeq,
		arg.SettledBelow,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditProject = `-- name: PageTenantAuditProject :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = $1 AND project_id = $2
    AND seq > $3 AND seq < $4
    AND recorded_at >= $5 AND recorded_at <= $6
ORDER BY seq LIMIT $7
`

type PageTenantAuditProjectParams struct {
	ChainOrgID     string
	ChainProjectID pgtype.Text
	AfterSeq       int64
	SettledBelow   int64
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	PageLimit      int32
}

func (q *Queries) PageTenantAuditProject(ctx context.Context, arg PageTenantAuditProjectParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.Query(ctx, pageTenantAuditProject,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.AfterSeq,
		arg.SettledBelow,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settledBelowInstance = `-- name: SettledBelowInstance :one
SELECT COALESCE(MIN(seq), 9223372036854775807)::bigint AS settled_below
FROM audit_instance_events WHERE txid >= $1
`

func (q *Queries) SettledBelowInstance(ctx context.Context, threshold int64) (int64, error) {
	row := q.db.QueryRow(ctx, settledBelowInstance, threshold)
	var settled_below int64
	err := row.Scan(&settled_below)
	return settled_below, err
}

const settledBelowTenant = `-- name: SettledBelowTenant :one
SELECT COALESCE(MIN(seq), 9223372036854775807)::bigint AS settled_below
FROM audit_tenant_events WHERE org_id = $1 AND txid >= $2
`

type SettledBelowTenantParams struct {
	ChainOrgID string
	Threshold  int64
}

func (q *Queries) SettledBelowTenant(ctx context.Context, arg SettledBelowTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, settledBelowTenant, arg.ChainOrgID, arg.Threshold)
	var settled_below int64
	err := row.Scan(&settled_below)
	return settled_below, err
}
