// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authn.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advancePrincipalGeneration = `-- name: AdvancePrincipalGeneration :exec
UPDATE principals SET session_generation = session_generation + 1 WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) AdvancePrincipalGeneration(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, advancePrincipalGeneration, id)
	return err
}

const advanceTOTPStep = `-- name: AdvanceTOTPStep :execrows
UPDATE totp_credentials SET last_step = $1, row_version = row_version + 1
WHERE id = $2 AND row_version = $3 AND last_step < $4
`

type AdvanceTOTPStepParams struct {
	LastStep   int64
	ID         string
	RowVersion int64
	LastStep_2 int64
}

// Single-use per (account, step): a code is consumed only if its step is
// strictly beyond the last one, which the CAS enforces atomically.
// hikyo:authn-resolution
func (q *Queries) AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTOTPStep,
		arg.LastStep,
		arg.ID,
		arg.RowVersion,
		arg.LastStep_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmTOTP = `-- name: ConfirmTOTP :execrows
UPDATE totp_credentials
SET confirmed_at = $1, last_step = $2, row_version = row_version + 1
WHERE id = $3 AND row_version = $4 AND confirmed_at IS NULL AND last_step < $5
`

type ConfirmTOTPParams struct {
	ConfirmedAt pgtype.Timestamptz
	LastStep    int64
	ID          string
	RowVersion  int64
	LastStep_2  int64
}

// Confirmation is the account-security mutation's write: it promotes the
// pending seed and consumes the confirming step in one CAS.
// hikyo:authn-resolution
func (q *Queries) ConfirmTOTP(ctx context.Context, arg ConfirmTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTOTP,
		arg.ConfirmedAt,
		arg.LastStep,
		arg.ID,
		arg.RowVersion,
		arg.LastStep_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeCredentialAuthority = `-- name: ConsumeCredentialAuthority :execrows
UPDATE credential_authorities SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
`

type ConsumeCredentialAuthorityParams struct {
	ConsumedAt pgtype.Timestamptz
	ID         string
}

// Single-use consumption: the NULL guard is the atomic claim, so two
// concurrent presentations cannot both establish a credential.
// hikyo:authn-resolution
func (q *Queries) ConsumeCredentialAuthority(ctx context.Context, arg ConsumeCredentialAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCredentialAuthority, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOIDCTransaction = `-- name: ConsumeOIDCTransaction :execrows
UPDATE oidc_transactions SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
`

type ConsumeOIDCTransactionParams struct {
	ConsumedAt pgtype.Timestamptz
	ID         string
}

// Single-use consumption: the NULL guard is the atomic claim, so a callback
// cannot be replayed and two concurrent callbacks cannot both consume one tx.
// hikyo:authn-resolution
func (q *Queries) ConsumeOIDCTransaction(ctx context.Context, arg ConsumeOIDCTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOIDCTransaction, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOutstandingAuthoritiesForAccount = `-- name: ConsumeOutstandingAuthoritiesForAccount :exec
UPDATE credential_authorities SET consumed_at = $1
WHERE account_id = $2 AND consumed_at IS NULL
`

type ConsumeOutstandingAuthoritiesForAccountParams struct {
	ConsumedAt pgtype.Timestamptz
	AccountID  string
}

// Minting an establishment authority for an account consumes every other
// outstanding one, so a second live reset token cannot linger past the point
// the operator believes the flow completed.
// hikyo:authn-resolution
func (q *Queries) ConsumeOutstandingAuthoritiesForAccount(ctx context.Context, arg ConsumeOutstandingAuthoritiesForAccountParams) error {
	_, err := q.db.Exec(ctx, consumeOutstandingAuthoritiesForAccount, arg.ConsumedAt, arg.AccountID)
	return err
}

const consumeSingleDecisionWindow = `-- name: ConsumeSingleDecisionWindow :execrows
UPDATE reauth_windows SET consumed_at = $1
WHERE id = $2 AND single_decision = 1 AND consumed_at IS NULL
`

type ConsumeSingleDecisionWindowParams struct {
	ConsumedAt pgtype.Timestamptz
	ID         string
}

// Claim a single_decision window exactly once: the NULL guard is the atomic
// claim, so a second disclosure loses and is refused (B11 double-spend).
// hikyo:authn-resolution
func (q *Queries) ConsumeSingleDecisionWindow(ctx context.Context, arg ConsumeSingleDecisionWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeSingleDecisionWindow, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

// hikyo:authn-resolution
func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExternalIdentity = `-- name: DeleteExternalIdentity :exec
DELETE FROM external_identities WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeleteExternalIdentity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteExternalIdentity, id)
	return err
}

const deletePendingTOTPForAccount = `-- name: DeletePendingTOTPForAccount :exec
DELETE FROM totp_credentials WHERE account_id = $1 AND confirmed_at IS NULL
`

// hikyo:authn-resolution
func (q *Queries) DeletePendingTOTPForAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deletePendingTOTPForAccount, accountID)
	return err
}

const deleteReauthWindowsForEnvironment = `-- name: DeleteReauthWindowsForEnvironment :execrows
DELETE FROM reauth_windows WHERE environment_id = $1
`

// Invalidate every open window on one environment: the first of LowerEffective
// Window's five ADR items on the effective-window transition (#54 B6).
// hikyo:authn-resolution
func (q *Queries) DeleteReauthWindowsForEnvironment(ctx context.Context, environmentID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReauthWindowsForEnvironment, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsForPrincipal = `-- name: DeleteSessionsForPrincipal :exec
DELETE FROM sessions WHERE principal_id = $1
`

// Every session of the principal dies, atomically and without reaching the
// client  -  the invalidation that token rotation structurally cannot do.
// hikyo:authn-resolution
func (q *Queries) DeleteSessionsForPrincipal(ctx context.Context, principalID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsForPrincipal, principalID)
	return err
}

const deleteSessionsForProvider = `-- name: DeleteSessionsForProvider :execrows
DELETE FROM sessions WHERE provider_id = $1
`

// The federated-session sweep (A4): every session minted through a provider
// dies when the provider's issuer/client/assurance policy changes or the
// provider is disabled or deleted. reauth_windows cascade from the session.
// hikyo:authn-resolution
func (q *Queries) DeleteSessionsForProvider(ctx context.Context, providerID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsForProvider, providerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTOTPForAccount = `-- name: DeleteTOTPForAccount :exec
DELETE FROM totp_credentials WHERE account_id = $1
`

// hikyo:authn-resolution
func (q *Queries) DeleteTOTPForAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteTOTPForAccount, accountID)
	return err
}

const environmentChainByID = `-- name: EnvironmentChainByID :one
SELECT org_id, project_id, id FROM environments WHERE id = $1
`

type EnvironmentChainByIDRow struct {
	OrgID     string
	ProjectID string
	ID        string
}

// Resolve an environment's chain from its id alone, for LowerEffectiveWindow's
// stranded-principal query (#54 B6): the denormalized chain columns make the row
// self-describing, so the grant-coverage predicate can be built from an env id.
// hikyo:authn-resolution
func (q *Queries) EnvironmentChainByID(ctx context.Context, id string) (EnvironmentChainByIDRow, error) {
	row := q.db.QueryRow(ctx, environmentChainByID, id)
	var i EnvironmentChainByIDRow
	err := row.Scan(&i.OrgID, &i.ProjectID, &i.ID)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, principal_id, username, display_name, created_at FROM accounts
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByPrincipal = `-- name: GetAccountByPrincipal :one
SELECT id, principal_id, username, display_name, created_at FROM accounts
WHERE principal_id = $1
`

type GetAccountByPrincipalRow struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) GetAccountByPrincipal(ctx context.Context, principalID string) (GetAccountByPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getAccountByPrincipal, principalID)
	var i GetAccountByPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, principal_id, username, display_name, created_at FROM accounts
WHERE username = $1
`

type GetAccountByUsernameRow struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getConfirmedTOTPForAccount = `-- name: GetConfirmedTOTPForAccount :one

SELECT id, account_id, seed, dek_version, credential_epoch, row_version,
       last_step, created_step, confirmed_at, created_at
FROM totp_credentials WHERE account_id = $1 AND confirmed_at IS NOT NULL
`

// Factors (#54, human-auth ADR). TOTP, recovery codes and the session-rotation
// writers join the enumerated resolution surface for the same reason the login
// writers did: they mutate the artifacts that decide how strongly a caller
// authenticated, which is resolved rather than authorized.
// hikyo:authn-resolution
func (q *Queries) GetConfirmedTOTPForAccount(ctx context.Context, accountID string) (TotpCredential, error) {
	row := q.db.QueryRow(ctx, getConfirmedTOTPForAccount, accountID)
	var i TotpCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seed,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.LastStep,
		&i.CreatedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialAuthorityByVerifier = `-- name: GetCredentialAuthorityByVerifier :one
SELECT id, account_id, verifier, purpose, issued_by, credential_epoch, expires_at,
       consumed_at, created_at
FROM credential_authorities WHERE verifier = $1
`

type GetCredentialAuthorityByVerifierRow struct {
	ID              string
	AccountID       string
	Verifier        []byte
	Purpose         string
	IssuedBy        string
	CredentialEpoch int64
	ExpiresAt       pgtype.Timestamptz
	ConsumedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) GetCredentialAuthorityByVerifier(ctx context.Context, verifier []byte) (GetCredentialAuthorityByVerifierRow, error) {
	row := q.db.QueryRow(ctx, getCredentialAuthorityByVerifier, verifier)
	var i GetCredentialAuthorityByVerifierRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Verifier,
		&i.Purpose,
		&i.IssuedBy,
		&i.CredentialEpoch,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialEpoch = `-- name: GetCredentialEpoch :one

SELECT credential_epoch FROM auth_instance_state WHERE id = 1
`

// Human authentication (#47, human-auth ADR). These live in the resolution
// surface for the same reason chain resolution does: deciding WHO a caller is
// cannot run under a proof, because the proof is what the answer produces.
// The write paths below are enumerated and pinned; anything else that mutates
// inside this surface fails the sole-writer analyzer.
// hikyo:authn-resolution
func (q *Queries) GetCredentialEpoch(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getCredentialEpoch)
	var credential_epoch int64
	err := row.Scan(&credential_epoch)
	return credential_epoch, err
}

const getEnabledProviderByIssuer = `-- name: GetEnabledProviderByIssuer :one

SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, jit_policy, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers WHERE kind = $1 AND issuer = $2 AND enabled = 1
`

type GetEnabledProviderByIssuerParams struct {
	Kind   string
	Issuer string
}

// OIDC login/link/reauth resolution (#54, human-auth ADR -- The OIDC
// transaction). These read providers, transactions and external identities
// with request-supplied identifiers, and write the transaction/identity/session
// rows that decide who a caller is: the resolution surface, proof-free, for the
// same reason the login writers are.
// hikyo:authn-resolution
func (q *Queries) GetEnabledProviderByIssuer(ctx context.Context, arg GetEnabledProviderByIssuerParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getEnabledProviderByIssuer, arg.Kind, arg.Issuer)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.RedirectUri,
		&i.JitPolicy,
		&i.AssurancePolicy,
		&i.Enabled,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledProviderBySlug = `-- name: GetEnabledProviderBySlug :one
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, jit_policy, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers WHERE slug = $1 AND enabled = 1
`

// Start resolves the provider by slug for an enabled provider only: a login,
// link or reauth may only begin against a provider that is currently serving.
// hikyo:authn-resolution
func (q *Queries) GetEnabledProviderBySlug(ctx context.Context, slug string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getEnabledProviderBySlug, slug)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.RedirectUri,
		&i.JitPolicy,
		&i.AssurancePolicy,
		&i.Enabled,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT id, account_id, kind, issuer, subject, provider_id, credential_epoch, created_at
FROM external_identities WHERE kind = $1 AND issuer = $2 AND subject = $3
`

type GetExternalIdentityParams struct {
	Kind    string
	Issuer  string
	Subject string
}

// hikyo:authn-resolution
func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getExternalIdentity, arg.Kind, arg.Issuer, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Issuer,
		&i.Subject,
		&i.ProviderID,
		&i.CredentialEpoch,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalIdentityByID = `-- name: GetExternalIdentityByID :one
SELECT id, account_id, kind, issuer, subject, provider_id, credential_epoch, created_at
FROM external_identities WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) GetExternalIdentityByID(ctx context.Context, id string) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityByID, id)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Issuer,
		&i.Subject,
		&i.ProviderID,
		&i.CredentialEpoch,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCTransactionByState = `-- name: GetOIDCTransactionByState :one
SELECT id, state_verifier, nonce, pkce_verifier, provider_id, issuer, redirect_uri,
       purpose, binding_kind, initiating_session_id, browser_binding_verifier,
       account_id, environment_id, ceremony_id, credential_epoch, created_at,
       expires_at, consumed_at
FROM oidc_transactions WHERE state_verifier = $1
`

// hikyo:authn-resolution
func (q *Queries) GetOIDCTransactionByState(ctx context.Context, stateVerifier []byte) (OidcTransaction, error) {
	row := q.db.QueryRow(ctx, getOIDCTransactionByState, stateVerifier)
	var i OidcTransaction
	err := row.Scan(
		&i.ID,
		&i.StateVerifier,
		&i.Nonce,
		&i.PkceVerifier,
		&i.ProviderID,
		&i.Issuer,
		&i.RedirectUri,
		&i.Purpose,
		&i.BindingKind,
		&i.InitiatingSessionID,
		&i.BrowserBindingVerifier,
		&i.AccountID,
		&i.EnvironmentID,
		&i.CeremonyID,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getOrgIdentity = `-- name: GetOrgIdentity :one
SELECT id, name FROM orgs WHERE id = $1
`

type GetOrgIdentityRow struct {
	ID   string
	Name string
}

// The org rail's identity lookup (#56). The caller's own org set is projected
// from their own grant rows, so there is no scope to authorize against and no
// proof to bind: the projection IS the authorization, and it can name only
// organisations the caller already holds a grant in. Identity only - an org's
// metadata and active flag are operator-set state and are read through the
// proof-gated GetOrg.
//
// Not annotated, and it does not need to be: orgs is class=org chain=id, and
// the id equality is that chain as a top-level conjunct.
func (q *Queries) GetOrgIdentity(ctx context.Context, id string) (GetOrgIdentityRow, error) {
	row := q.db.QueryRow(ctx, getOrgIdentity, id)
	var i GetOrgIdentityRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT account_id, verifier, kdf_memory_kib, kdf_time, kdf_parallelism,
       dek_version, credential_epoch, row_version, updated_at
FROM password_credentials WHERE account_id = $1
`

// hikyo:authn-resolution
func (q *Queries) GetPasswordCredential(ctx context.Context, accountID string) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, accountID)
	var i PasswordCredential
	err := row.Scan(
		&i.AccountID,
		&i.Verifier,
		&i.KdfMemoryKib,
		&i.KdfTime,
		&i.KdfParallelism,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTOTPForAccount = `-- name: GetPendingTOTPForAccount :one
SELECT id, account_id, seed, dek_version, credential_epoch, row_version,
       last_step, created_step, confirmed_at, created_at
FROM totp_credentials WHERE account_id = $1 AND confirmed_at IS NULL
`

// hikyo:authn-resolution
func (q *Queries) GetPendingTOTPForAccount(ctx context.Context, accountID string) (TotpCredential, error) {
	row := q.db.QueryRow(ctx, getPendingTOTPForAccount, accountID)
	var i TotpCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seed,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.LastStep,
		&i.CreatedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipalGeneration = `-- name: GetPrincipalGeneration :one
SELECT session_generation FROM principals WHERE id = $1
`

// hikyo:authn-resolution
func (q *Queries) GetPrincipalGeneration(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getPrincipalGeneration, id)
	var session_generation int64
	err := row.Scan(&session_generation)
	return session_generation, err
}

const getPrincipalKind = `-- name: GetPrincipalKind :one

SELECT kind FROM principals WHERE id = $1
`

// The denial writer's actor-class lookup (#45, audit-model ADR amendment
// part 4): the flush transaction resolves the denied principal's kind for
// the event's actor class. Runs only inside authn.WriteDenial.
// hikyo:authn-resolution
func (q *Queries) GetPrincipalKind(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPrincipalKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getProviderForCallback = `-- name: GetProviderForCallback :one
SELECT id, slug, display_name, kind, issuer, client_id, client_secret, scopes,
       redirect_uri, jit_policy, assurance_policy, enabled, dek_version, row_version,
       created_at, updated_at
FROM oidc_providers WHERE id = $1
`

// The recorded provider a callback exchanges at (A11): loaded by the id the
// transaction pinned, so the exchange happens only at that provider.
// hikyo:authn-resolution
func (q *Queries) GetProviderForCallback(ctx context.Context, id string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getProviderForCallback, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.RedirectUri,
		&i.JitPolicy,
		&i.AssurancePolicy,
		&i.Enabled,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReauthWindow = `-- name: GetReauthWindow :one
SELECT id, session_id, environment_id, ceremony_id, factor_class, single_decision,
       authenticated_at, window_expires_at, hard_expires_at, credential_epoch,
       consumed_at, created_at
FROM reauth_windows WHERE session_id = $1 AND environment_id = $2
`

type GetReauthWindowParams struct {
	SessionID     string
	EnvironmentID string
}

// Reauth-window consumption at disclosure (#54, human-auth ADR - Reauthentication).
// A disclosure on environment E requires a live window for (session, E). These
// read the window, slide its sliding clock (never past the hard cap the service
// enforces), and claim a single_decision window exactly once via the consumed_at
// NULL guard. There is no reveal operation to call these yet (#50/#58); they ship
// as the library those verticals consume, exercised directly by fixtures.
// hikyo:authn-resolution
func (q *Queries) GetReauthWindow(ctx context.Context, arg GetReauthWindowParams) (ReauthWindow, error) {
	row := q.db.QueryRow(ctx, getReauthWindow, arg.SessionID, arg.EnvironmentID)
	var i ReauthWindow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EnvironmentID,
		&i.CeremonyID,
		&i.FactorClass,
		&i.SingleDecision,
		&i.AuthenticatedAt,
		&i.WindowExpiresAt,
		&i.HardExpiresAt,
		&i.CredentialEpoch,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecoveryCodes = `-- name: GetRecoveryCodes :one
SELECT account_id, batch, dek_version, credential_epoch, row_version, generated_at
FROM recovery_codes WHERE account_id = $1
`

// hikyo:authn-resolution
func (q *Queries) GetRecoveryCodes(ctx context.Context, accountID string) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, getRecoveryCodes, accountID)
	var i RecoveryCode
	err := row.Scan(
		&i.AccountID,
		&i.Batch,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.GeneratedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, principal_id, artifact, session_generation, credential_epoch,
       auth_method, factors, authenticated_at, ceremony_id, created_at,
       last_seen_at, idle_expires_at, absolute_expires_at, csrf_verifier
FROM sessions WHERE id = $1
`

type GetSessionByIDRow struct {
	ID                string
	PrincipalID       string
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   pgtype.Timestamptz
	CeremonyID        pgtype.Text
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	CsrfVerifier      []byte
}

// hikyo:authn-resolution
func (q *Queries) GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Artifact,
		&i.SessionGeneration,
		&i.CredentialEpoch,
		&i.AuthMethod,
		&i.Factors,
		&i.AuthenticatedAt,
		&i.CeremonyID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CsrfVerifier,
	)
	return i, err
}

const getSessionByVerifier = `-- name: GetSessionByVerifier :one
SELECT id, principal_id, verifier, artifact, session_generation, credential_epoch,
       auth_method, factors, authenticated_at, ceremony_id, created_at,
       last_seen_at, idle_expires_at, absolute_expires_at, csrf_verifier
FROM sessions WHERE verifier = $1
`

type GetSessionByVerifierRow struct {
	ID                string
	PrincipalID       string
	Verifier          []byte
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   pgtype.Timestamptz
	CeremonyID        pgtype.Text
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	CsrfVerifier      []byte
}

// hikyo:authn-resolution
func (q *Queries) GetSessionByVerifier(ctx context.Context, verifier []byte) (GetSessionByVerifierRow, error) {
	row := q.db.QueryRow(ctx, getSessionByVerifier, verifier)
	var i GetSessionByVerifierRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Verifier,
		&i.Artifact,
		&i.SessionGeneration,
		&i.CredentialEpoch,
		&i.AuthMethod,
		&i.Factors,
		&i.AuthenticatedAt,
		&i.CeremonyID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CsrfVerifier,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, principal_id, username, display_name, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAccountParams struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.PrincipalID,
		arg.Username,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const insertCredentialAuthority = `-- name: InsertCredentialAuthority :exec
INSERT INTO credential_authorities
    (id, verifier, account_id, purpose, issued_by, credential_epoch, expires_at, consumed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULL, $8)
`

type InsertCredentialAuthorityParams struct {
	ID              string
	Verifier        []byte
	AccountID       string
	Purpose         string
	IssuedBy        string
	CredentialEpoch int64
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertCredentialAuthority(ctx context.Context, arg InsertCredentialAuthorityParams) error {
	_, err := q.db.Exec(ctx, insertCredentialAuthority,
		arg.ID,
		arg.Verifier,
		arg.AccountID,
		arg.Purpose,
		arg.IssuedBy,
		arg.CredentialEpoch,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO external_identities
    (id, account_id, kind, issuer, subject, provider_id, credential_epoch, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertExternalIdentityParams struct {
	ID              string
	AccountID       string
	Kind            string
	Issuer          string
	Subject         string
	ProviderID      string
	CredentialEpoch int64
	CreatedAt       pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExternalIdentity,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Issuer,
		arg.Subject,
		arg.ProviderID,
		arg.CredentialEpoch,
		arg.CreatedAt,
	)
	return err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO grants (id, principal_id, capability, org_id, project_id, env_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertGrantParams struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       pgtype.Text
	ProjectID   pgtype.Text
	EnvID       pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.ID,
		arg.PrincipalID,
		arg.Capability,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.CreatedAt,
	)
	return err
}

const insertOIDCTransaction = `-- name: InsertOIDCTransaction :exec
INSERT INTO oidc_transactions
    (id, state_verifier, nonce, pkce_verifier, provider_id, issuer, redirect_uri,
     purpose, binding_kind, initiating_session_id, browser_binding_verifier,
     account_id, environment_id, ceremony_id, credential_epoch, created_at,
     expires_at, consumed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, NULL)
`

type InsertOIDCTransactionParams struct {
	ID                     string
	StateVerifier          []byte
	Nonce                  []byte
	PkceVerifier           string
	ProviderID             string
	Issuer                 string
	RedirectUri            string
	Purpose                string
	BindingKind            string
	InitiatingSessionID    pgtype.Text
	BrowserBindingVerifier []byte
	AccountID              pgtype.Text
	EnvironmentID          pgtype.Text
	CeremonyID             pgtype.Text
	CredentialEpoch        int64
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertOIDCTransaction(ctx context.Context, arg InsertOIDCTransactionParams) error {
	_, err := q.db.Exec(ctx, insertOIDCTransaction,
		arg.ID,
		arg.StateVerifier,
		arg.Nonce,
		arg.PkceVerifier,
		arg.ProviderID,
		arg.Issuer,
		arg.RedirectUri,
		arg.Purpose,
		arg.BindingKind,
		arg.InitiatingSessionID,
		arg.BrowserBindingVerifier,
		arg.AccountID,
		arg.EnvironmentID,
		arg.CeremonyID,
		arg.CredentialEpoch,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertPasswordCredential = `-- name: InsertPasswordCredential :exec
INSERT INTO password_credentials
    (account_id, verifier, kdf_memory_kib, kdf_time, kdf_parallelism,
     dek_version, credential_epoch, row_version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, $8)
`

type InsertPasswordCredentialParams struct {
	AccountID       string
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	UpdatedAt       pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertPasswordCredential(ctx context.Context, arg InsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, insertPasswordCredential,
		arg.AccountID,
		arg.Verifier,
		arg.KdfMemoryKib,
		arg.KdfTime,
		arg.KdfParallelism,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.UpdatedAt,
	)
	return err
}

const insertPrincipal = `-- name: InsertPrincipal :exec

INSERT INTO principals (id, kind, created_at, session_generation)
VALUES ($1, $2, $3, 1)
`

type InsertPrincipalParams struct {
	ID        string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

// Enumerated writers.
// hikyo:authn-resolution
func (q *Queries) InsertPrincipal(ctx context.Context, arg InsertPrincipalParams) error {
	_, err := q.db.Exec(ctx, insertPrincipal, arg.ID, arg.Kind, arg.CreatedAt)
	return err
}

const insertReauthWindow = `-- name: InsertReauthWindow :exec
INSERT INTO reauth_windows
    (id, session_id, environment_id, ceremony_id, factor_class, single_decision,
     authenticated_at, window_expires_at, hard_expires_at, credential_epoch,
     consumed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NULL, $11)
`

type InsertReauthWindowParams struct {
	ID              string
	SessionID       string
	EnvironmentID   string
	CeremonyID      string
	FactorClass     string
	SingleDecision  int64
	AuthenticatedAt pgtype.Timestamptz
	WindowExpiresAt pgtype.Timestamptz
	HardExpiresAt   pgtype.Timestamptz
	CredentialEpoch int64
	CreatedAt       pgtype.Timestamptz
}

// A reauthentication window opened by a possession-factor ceremony. OIDC reauth
// opens one only where the effective window is > 0; a WebAuthn ceremony can bind
// the enumerated unit, so at a 0 effective window it opens a single_decision
// window (B11) consumed by exactly one enumerated decision. Keyed by session,
// cascading with it.
// hikyo:authn-resolution
func (q *Queries) InsertReauthWindow(ctx context.Context, arg InsertReauthWindowParams) error {
	_, err := q.db.Exec(ctx, insertReauthWindow,
		arg.ID,
		arg.SessionID,
		arg.EnvironmentID,
		arg.CeremonyID,
		arg.FactorClass,
		arg.SingleDecision,
		arg.AuthenticatedAt,
		arg.WindowExpiresAt,
		arg.HardExpiresAt,
		arg.CredentialEpoch,
		arg.CreatedAt,
	)
	return err
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec
INSERT INTO recovery_codes
    (account_id, batch, dek_version, credential_epoch, row_version, generated_at)
VALUES ($1, $2, $3, $4, 1, $5)
`

type InsertRecoveryCodesParams struct {
	AccountID       string
	Batch           []byte
	DekVersion      int64
	CredentialEpoch int64
	GeneratedAt     pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCodes,
		arg.AccountID,
		arg.Batch,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.GeneratedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions
    (id, principal_id, verifier, artifact, session_generation, credential_epoch,
     auth_method, factors, authenticated_at, ceremony_id, created_at,
     last_seen_at, idle_expires_at, absolute_expires_at, source_ip, user_agent,
     provider_id, csrf_verifier)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertSessionParams struct {
	ID                string
	PrincipalID       string
	Verifier          []byte
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   pgtype.Timestamptz
	CeremonyID        pgtype.Text
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	SourceIp          string
	UserAgent         string
	ProviderID        pgtype.Text
	CsrfVerifier      []byte
}

// hikyo:authn-resolution
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.PrincipalID,
		arg.Verifier,
		arg.Artifact,
		arg.SessionGeneration,
		arg.CredentialEpoch,
		arg.AuthMethod,
		arg.Factors,
		arg.AuthenticatedAt,
		arg.CeremonyID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.SourceIp,
		arg.UserAgent,
		arg.ProviderID,
		arg.CsrfVerifier,
	)
	return err
}

const insertTOTP = `-- name: InsertTOTP :exec
INSERT INTO totp_credentials
    (id, account_id, seed, dek_version, credential_epoch, row_version,
     last_step, created_step, confirmed_at, created_at)
VALUES ($1, $2, $3, $4, $5, 1, $6, $7, NULL, $8)
`

type InsertTOTPParams struct {
	ID              string
	AccountID       string
	Seed            []byte
	DekVersion      int64
	CredentialEpoch int64
	LastStep        int64
	CreatedStep     int64
	CreatedAt       pgtype.Timestamptz
}

// hikyo:authn-resolution
func (q *Queries) InsertTOTP(ctx context.Context, arg InsertTOTPParams) error {
	_, err := q.db.Exec(ctx, insertTOTP,
		arg.ID,
		arg.AccountID,
		arg.Seed,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.LastStep,
		arg.CreatedStep,
		arg.CreatedAt,
	)
	return err
}

const listExternalIdentitiesForAccount = `-- name: ListExternalIdentitiesForAccount :many
SELECT id, account_id, kind, issuer, subject, provider_id, credential_epoch, created_at
FROM external_identities WHERE account_id = $1 ORDER BY created_at
`

// hikyo:authn-resolution
func (q *Queries) ListExternalIdentitiesForAccount(ctx context.Context, accountID string) ([]ExternalIdentity, error) {
	rows, err := q.db.Query(ctx, listExternalIdentitiesForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalIdentity
	for rows.Next() {
		var i ExternalIdentity
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Issuer,
			&i.Subject,
			&i.ProviderID,
			&i.CredentialEpoch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForPrincipal = `-- name: ListGrantsForPrincipal :many
SELECT capability, org_id, project_id, env_id FROM grants
WHERE principal_id = $1
`

type ListGrantsForPrincipalRow struct {
	Capability string
	OrgID      pgtype.Text
	ProjectID  pgtype.Text
	EnvID      pgtype.Text
}

// hikyo:authn-resolution
func (q *Queries) ListGrantsForPrincipal(ctx context.Context, principalID string) ([]ListGrantsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForPrincipalRow
	for rows.Next() {
		var i ListGrantsForPrincipalRow
		if err := rows.Scan(
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForResetTarget = `-- name: ListGrantsForResetTarget :many
SELECT capability, org_id, project_id, env_id FROM grants
WHERE principal_id = $1
`

type ListGrantsForResetTargetRow struct {
	Capability string
	OrgID      pgtype.Text
	ProjectID  pgtype.Text
	EnvID      pgtype.Text
}

// The target principal's grant set, for the credential-reset org-bounded test
// (#54 credential-reset, ADR - Recovery): reset reaches only a target whose grants
// lie entirely within one org and who holds no instance capability.
// hikyo:authn-resolution
func (q *Queries) ListGrantsForResetTarget(ctx context.Context, principalID string) ([]ListGrantsForResetTargetRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForResetTarget, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForResetTargetRow
	for rows.Next() {
		var i ListGrantsForResetTargetRow
		if err := rows.Scan(
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrincipalRow = `-- name: LockPrincipalRow :one
SELECT id FROM principals WHERE id = $1 FOR UPDATE
`

// Principal row lock (#54 B14): every grant writer takes it so the credential-
// reset org-bounded test serializes against a concurrent grant landing. sqlite's
// single writer serializes trivially; postgres takes FOR UPDATE. The grant-lock
// analyzer pins that this sits inside every grant writer.
// hikyo:authn-resolution
func (q *Queries) LockPrincipalRow(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockPrincipalRow, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const rebindSAMLExternalIdentityProvider = `-- name: RebindSAMLExternalIdentityProvider :execrows
UPDATE external_identities
SET provider_id = $1
WHERE id = $2
  AND kind = 'saml'
  AND provider_id = $3
`

type RebindSAMLExternalIdentityProviderParams struct {
	NewProviderID      string
	ID                 string
	ExpectedProviderID string
}

// Re-adding the same byte-exact SAML entity creates a new provider row while
// preserving the human link. The old provider id is a provenance CAS guard:
// only the identity just verified by that entity may move to the live row.
// hikyo:authn-resolution
func (q *Queries) RebindSAMLExternalIdentityProvider(ctx context.Context, arg RebindSAMLExternalIdentityProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, rebindSAMLExternalIdentityProvider, arg.NewProviderID, arg.ID, arg.ExpectedProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveEnvChain = `-- name: ResolveEnvChain :one
SELECT org_id, project_id, id FROM environments
WHERE org_id = $1 AND project_id = $2 AND id = $3
`

type ResolveEnvChainParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

type ResolveEnvChainRow struct {
	OrgID     string
	ProjectID string
	ID        string
}

// hikyo:authn-resolution
func (q *Queries) ResolveEnvChain(ctx context.Context, arg ResolveEnvChainParams) (ResolveEnvChainRow, error) {
	row := q.db.QueryRow(ctx, resolveEnvChain, arg.OrgID, arg.ProjectID, arg.ID)
	var i ResolveEnvChainRow
	err := row.Scan(&i.OrgID, &i.ProjectID, &i.ID)
	return i, err
}

const resolveOrgChain = `-- name: ResolveOrgChain :one


SELECT id FROM orgs WHERE id = $1
`

// The authorization package's enumerated resolution surface (tenant-isolation
// ADR bootstrap carve-out): the only statements that read chain tables with
// request-supplied identifiers, because authorize() runs them to mint the
// proof everything else requires. Each is annotated and content-pinned in the
// allowlist fixture - drift fails the build until re-reviewed.
// Chain resolution is one query, one round trip, regardless of which level
// is missing: the denormalized chain columns plus composite ancestry FKs make
// the addressed row's own chain authoritative, so no per-level walk exists.
// hikyo:authn-resolution
func (q *Queries) ResolveOrgChain(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, resolveOrgChain, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const resolveProjectChain = `-- name: ResolveProjectChain :one
SELECT org_id, id FROM projects WHERE org_id = $1 AND id = $2
`

type ResolveProjectChainParams struct {
	OrgID string
	ID    string
}

type ResolveProjectChainRow struct {
	OrgID string
	ID    string
}

// hikyo:authn-resolution
func (q *Queries) ResolveProjectChain(ctx context.Context, arg ResolveProjectChainParams) (ResolveProjectChainRow, error) {
	row := q.db.QueryRow(ctx, resolveProjectChain, arg.OrgID, arg.ID)
	var i ResolveProjectChainRow
	err := row.Scan(&i.OrgID, &i.ID)
	return i, err
}

const rotateSessionFactors = `-- name: RotateSessionFactors :exec
UPDATE sessions SET verifier = $1, factors = $2 WHERE id = $3
`

type RotateSessionFactorsParams struct {
	Verifier []byte
	Factors  string
	ID       string
}

// Step-up rotates the session token and rewrites its factor set; the original
// authenticated_at and ceremony_id are preserved so absolute-age attribution
// cannot be reset by repeated step-ups.
// hikyo:authn-resolution
func (q *Queries) RotateSessionFactors(ctx context.Context, arg RotateSessionFactorsParams) error {
	_, err := q.db.Exec(ctx, rotateSessionFactors, arg.Verifier, arg.Factors, arg.ID)
	return err
}

const slideReauthWindow = `-- name: SlideReauthWindow :execrows
UPDATE reauth_windows SET window_expires_at = $1
WHERE id = $2 AND single_decision = 0 AND consumed_at IS NULL
`

type SlideReauthWindowParams struct {
	WindowExpiresAt pgtype.Timestamptz
	ID              string
}

// Slide the idle window clock on a sliding (non single-decision) window. The hard
// cap is enforced by the service, which passes min(now+window, hard_expires_at);
// the NULL guard keeps a concurrently-claimed window from sliding.
// hikyo:authn-resolution
func (q *Queries) SlideReauthWindow(ctx context.Context, arg SlideReauthWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, slideReauthWindow, arg.WindowExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const strandedRevealPrincipalsForEnvironment = `-- name: StrandedRevealPrincipalsForEnvironment :many
SELECT DISTINCT g.principal_id
FROM grants g
WHERE g.capability IN ('reveal', 'reveal-history')
  AND (g.org_id IS NULL
       OR (g.org_id = $1 AND g.project_id IS NULL)
       OR (g.org_id = $1 AND g.project_id = $2 AND g.env_id IS NULL)
       OR (g.org_id = $1 AND g.project_id = $2 AND g.env_id = $3))
  AND NOT EXISTS (
      SELECT 1 FROM webauthn_credentials w
      JOIN accounts a ON a.id = w.account_id
      WHERE a.principal_id = g.principal_id AND w.disabled_at IS NULL)
`

type StrandedRevealPrincipalsForEnvironmentParams struct {
	Org     pgtype.Text
	Project pgtype.Text
	Env     pgtype.Text
}

// Stranded-principal enumeration for LowerEffectiveWindow (#54 B6): principals
// holding reveal/reveal-history covering environment E (a grant at E, its project,
// its org, or the instance) who have no enabled WebAuthn authenticator, so a 0
// effective window fails their disclosure closed until they enrol one.
// hikyo:authn-resolution
func (q *Queries) StrandedRevealPrincipalsForEnvironment(ctx context.Context, arg StrandedRevealPrincipalsForEnvironmentParams) ([]string, error) {
	rows, err := q.db.Query(ctx, strandedRevealPrincipalsForEnvironment, arg.Org, arg.Project, arg.Env)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var principal_id string
		if err := rows.Scan(&principal_id); err != nil {
			return nil, err
		}
		items = append(items, principal_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1, idle_expires_at = $2 WHERE id = $3
`

type TouchSessionParams struct {
	LastSeenAt    pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	ID            string
}

// hikyo:authn-resolution
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastSeenAt, arg.IdleExpiresAt, arg.ID)
	return err
}

const updatePasswordCredentialCAS = `-- name: UpdatePasswordCredentialCAS :execrows
UPDATE password_credentials
SET verifier = $1, kdf_memory_kib = $2, kdf_time = $3, kdf_parallelism = $4,
    dek_version = $5, credential_epoch = $6, row_version = row_version + 1,
    updated_at = $7
WHERE account_id = $8 AND row_version = $9
`

type UpdatePasswordCredentialCASParams struct {
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	UpdatedAt       pgtype.Timestamptz
	AccountID       string
	RowVersion      int64
}

// Compare-and-swap on row_version: a resumable, lock-free `reencrypt` racing
// a password reset would otherwise write the stale verifier back under the
// new DEK version and silently resurrect a superseded password.
// hikyo:authn-resolution
func (q *Queries) UpdatePasswordCredentialCAS(ctx context.Context, arg UpdatePasswordCredentialCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordCredentialCAS,
		arg.Verifier,
		arg.KdfMemoryKib,
		arg.KdfTime,
		arg.KdfParallelism,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.UpdatedAt,
		arg.AccountID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRecoveryCodesCAS = `-- name: UpdateRecoveryCodesCAS :execrows
UPDATE recovery_codes
SET batch = $1, dek_version = $2, credential_epoch = $3,
    row_version = row_version + 1, generated_at = $4
WHERE account_id = $5 AND row_version = $6
`

type UpdateRecoveryCodesCASParams struct {
	Batch           []byte
	DekVersion      int64
	CredentialEpoch int64
	GeneratedAt     pgtype.Timestamptz
	AccountID       string
	RowVersion      int64
}

// Regeneration and consumption both rewrite the batch under a CAS, so a
// concurrent second presentation of the same code loses and fails closed.
// hikyo:authn-resolution
func (q *Queries) UpdateRecoveryCodesCAS(ctx context.Context, arg UpdateRecoveryCodesCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecoveryCodesCAS,
		arg.Batch,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.GeneratedAt,
		arg.AccountID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
