// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :exec

INSERT INTO environments (id, org_id, project_id, name, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEnvironmentParams struct {
	ID             string
	ChainOrgID     string
	ChainProjectID string
	Name           string
	Note           string
	CreatedAt      pgtype.Timestamptz
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createEnvironment,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.Name,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, org_id, project_id, name, note, created_at FROM environments
WHERE org_id = $1 AND project_id = $2 AND id = $3
`

type GetEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const updateEnvironmentNote = `-- name: UpdateEnvironmentNote :execrows
UPDATE environments SET note = $1
WHERE org_id = $2 AND project_id = $3 AND id = $4
`

type UpdateEnvironmentNoteParams struct {
	Note           string
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) UpdateEnvironmentNote(ctx context.Context, arg UpdateEnvironmentNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEnvironmentNote,
		arg.Note,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
