// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFolder = `-- name: CreateFolder :exec

INSERT INTO folders (id, org_id, project_id, path, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFolderParams struct {
	ID             string
	ChainOrgID     string
	ChainProjectID string
	Path           string
	CreatedAt      pgtype.Timestamptz
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
//
// A folder is addressed WITHIN the project the proof resolved: the chain
// conjuncts come from the proof, and `id` is an ordinary caller argument like
// `path` is. The scope lattice has no folder level (permission-model ADR: no
// folder-scoped grants), so there is no chain field for it to bind from - and
// it needs none: a folder id from another project simply misses the chain
// predicate, which is the uniform nonexistent outcome.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.Exec(ctx, createFolder,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.Path,
		arg.CreatedAt,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders WHERE org_id = $1 AND project_id = $2 AND id = $3
`

type DeleteFolderParams struct {
	ChainOrgID     string
	ChainProjectID string
	ID             string
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ChainOrgID, arg.ChainProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFolder = `-- name: GetFolder :one
SELECT id, org_id, project_id, path, created_at FROM folders
WHERE org_id = $1 AND project_id = $2 AND id = $3
`

type GetFolderParams struct {
	ChainOrgID     string
	ChainProjectID string
	ID             string
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, arg.ChainOrgID, arg.ChainProjectID, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, org_id, project_id, path, created_at FROM folders
WHERE org_id = $1 AND project_id = $2 ORDER BY path
`

type ListFoldersParams struct {
	ChainOrgID     string
	ChainProjectID string
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameFolder = `-- name: RenameFolder :execrows
UPDATE folders SET path = $1
WHERE org_id = $2 AND project_id = $3 AND id = $4
`

type RenameFolderParams struct {
	Path           string
	ChainOrgID     string
	ChainProjectID string
	ID             string
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameFolder,
		arg.Path,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
