// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyring.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireHierarchyGeneration = `-- name: AcquireHierarchyGeneration :one
SELECT generation FROM key_generations WHERE scope = 'hierarchy' FOR UPDATE
`

func (q *Queries) AcquireHierarchyGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, acquireHierarchyGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getActiveMasterKeys = `-- name: GetActiveMasterKeys :many
SELECT version, root_key_epoch, state, blob, created_at
FROM master_keys WHERE state = 'active' ORDER BY root_key_epoch DESC
`

func (q *Queries) GetActiveMasterKeys(ctx context.Context) ([]MasterKey, error) {
	rows, err := q.db.Query(ctx, getActiveMasterKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterKey
	for rows.Next() {
		var i MasterKey
		if err := rows.Scan(
			&i.Version,
			&i.RootKeyEpoch,
			&i.State,
			&i.Blob,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTier3Key = `-- name: GetActiveTier3Key :one
SELECT id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at
FROM tier3_keys WHERE purpose = $1 AND org_id = $2 AND project_id = $3 AND state = 'active'
`

type GetActiveTier3KeyParams struct {
	Purpose   string
	OrgID     string
	ProjectID string
}

func (q *Queries) GetActiveTier3Key(ctx context.Context, arg GetActiveTier3KeyParams) (Tier3Key, error) {
	row := q.db.QueryRow(ctx, getActiveTier3Key, arg.Purpose, arg.OrgID, arg.ProjectID)
	var i Tier3Key
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.OrgID,
		&i.ProjectID,
		&i.Version,
		&i.MasterKeyVersion,
		&i.State,
		&i.Blob,
		&i.CreatedAt,
	)
	return i, err
}

const insertKeyGeneration = `-- name: InsertKeyGeneration :exec
INSERT INTO key_generations (scope, generation) VALUES ($1, 1)
`

func (q *Queries) InsertKeyGeneration(ctx context.Context, scope string) error {
	_, err := q.db.Exec(ctx, insertKeyGeneration, scope)
	return err
}

const insertMasterKey = `-- name: InsertMasterKey :exec
INSERT INTO master_keys (version, root_key_epoch, state, blob, created_at)
VALUES ($1, $2, 'active', $3, $4)
`

type InsertMasterKeyParams struct {
	Version      int64
	RootKeyEpoch int64
	Blob         []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertMasterKey(ctx context.Context, arg InsertMasterKeyParams) error {
	_, err := q.db.Exec(ctx, insertMasterKey,
		arg.Version,
		arg.RootKeyEpoch,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}

const insertTier3Key = `-- name: InsertTier3Key :exec
INSERT INTO tier3_keys (id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 'active', $7, $8)
`

type InsertTier3KeyParams struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	Blob             []byte
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertTier3Key(ctx context.Context, arg InsertTier3KeyParams) error {
	_, err := q.db.Exec(ctx, insertTier3Key,
		arg.ID,
		arg.Purpose,
		arg.OrgID,
		arg.ProjectID,
		arg.Version,
		arg.MasterKeyVersion,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}
