// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pggen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Org struct {
	ID        string
	Name      string
	Active    bool
	Metadata  string
	CreatedAt pgtype.Timestamptz
}
