// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pggen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditInstanceEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

type AuditTenantEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int32
	OccurredAt        pgtype.Timestamptz
	OccurredAsserted  bool
	RecordedAt        pgtype.Timestamptz
	ActorID           pgtype.Text
	ActorClass        string
	ActorCredentialID pgtype.Text
	AuthorityID       pgtype.Text
	ScopeClass        string
	OrgID             string
	ProjectID         pgtype.Text
	EnvID             pgtype.Text
	ObjectType        pgtype.Text
	ObjectID          pgtype.Text
	Outcome           string
	CorrelationID     pgtype.Text
	SourceIp          pgtype.Text
	UserAgent         pgtype.Text
	Origin            string
	Payload           string
}

type Environment struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	Note      string
	CreatedAt pgtype.Timestamptz
}

type Grant struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       pgtype.Text
	ProjectID   pgtype.Text
	EnvID       pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type KeyGeneration struct {
	Scope      string
	Generation int64
}

type MasterKey struct {
	Version      int64
	RootKeyEpoch int64
	State        string
	Blob         []byte
	CreatedAt    pgtype.Timestamptz
}

type Org struct {
	ID        string
	Name      string
	Active    bool
	Metadata  string
	CreatedAt pgtype.Timestamptz
}

type Principal struct {
	ID        string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        string
	OrgID     string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Tier3Key struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	State            string
	Blob             []byte
	CreatedAt        pgtype.Timestamptz
}
