// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgs = `-- name: CountOrgs :one
SELECT COUNT(*) FROM orgs
`

func (q *Queries) CountOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :exec
INSERT INTO orgs (id, name, active, metadata, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrgParams struct {
	ID        string
	Name      string
	Active    bool
	Metadata  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) error {
	_, err := q.db.Exec(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, active, metadata, created_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, active, metadata, created_at FROM orgs ORDER BY name
`

func (q *Queries) ListOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
