// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec

INSERT INTO projects (id, org_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateProjectParams struct {
	ID         string
	ChainOrgID string
	Name       string
	CreatedAt  pgtype.Timestamptz
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.ChainOrgID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}
