// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRevisionPinsForProject = `-- name: CountRevisionPinsForProject :one
SELECT COUNT(*) FROM revision_pins
WHERE org_id = $1 AND project_id = $2
`

type CountRevisionPinsForProjectParams struct {
	ChainOrgID     string
	ChainProjectID string
}

func (q *Queries) CountRevisionPinsForProject(ctx context.Context, arg CountRevisionPinsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRevisionPinsForProject, arg.ChainOrgID, arg.ChainProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingChangeByID = `-- name: DeletePendingChangeByID :execrows
DELETE FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND id = $4
`

type DeletePendingChangeByIDParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	ID             string
}

func (q *Queries) DeletePendingChangeByID(ctx context.Context, arg DeletePendingChangeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingChangeByID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingChangeForCell = `-- name: DeletePendingChangeForCell :execrows
DELETE FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND key_id = $4
  AND owner_id = $5
`

type DeletePendingChangeForCellParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	KeyID          string
	OwnerID        string
}

// DeletePendingChangeForCell collects the superseded version. Editing a cell
// mints a new version id rather than mutating the old row, and the old row is
// removed in the same transaction: only the latest version per (owner, key,
// environment) is publishable, so keeping the predecessor would store draft
// material nothing may ever publish.
func (q *Queries) DeletePendingChangeForCell(ctx context.Context, arg DeletePendingChangeForCellParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingChangeForCell,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.KeyID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingChangesForEnvironment = `-- name: DeletePendingChangesForEnvironment :execrows
DELETE FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeletePendingChangesForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeletePendingChangesForEnvironment(ctx context.Context, arg DeletePendingChangesForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingChangesForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingChangesForKey = `-- name: DeletePendingChangesForKey :execrows
DELETE FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND key_id = $3
`

type DeletePendingChangesForKeyParams struct {
	ChainOrgID     string
	ChainProjectID string
	KeyID          string
}

// DeletePendingChangesForKey is the key-delete cascade: deleting a key
// invalidates every pending change referencing it, so a publish naming one of
// those versions is refused loudly instead of resurrecting a key the schema no
// longer declares.
func (q *Queries) DeletePendingChangesForKey(ctx context.Context, arg DeletePendingChangesForKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingChangesForKey, arg.ChainOrgID, arg.ChainProjectID, arg.KeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevisionKeyChangesForEnvironment = `-- name: DeleteRevisionKeyChangesForEnvironment :execrows
DELETE FROM revision_key_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteRevisionKeyChangesForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeleteRevisionKeyChangesForEnvironment(ctx context.Context, arg DeleteRevisionKeyChangesForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevisionKeyChangesForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevisionPin = `-- name: DeleteRevisionPin :execrows
DELETE FROM revision_pins
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
  AND workload_principal_id = $4
`

type DeleteRevisionPinParams struct {
	ChainOrgID          string
	ChainProjectID      string
	ChainEnvID          string
	WorkloadPrincipalID string
}

func (q *Queries) DeleteRevisionPin(ctx context.Context, arg DeleteRevisionPinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevisionPin,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.WorkloadPrincipalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevisionPinsForEnvironment = `-- name: DeleteRevisionPinsForEnvironment :execrows
DELETE FROM revision_pins
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteRevisionPinsForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeleteRevisionPinsForEnvironment(ctx context.Context, arg DeleteRevisionPinsForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevisionPinsForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSecretValueOccurrencesForEnvironment = `-- name: DeleteSecretValueOccurrencesForEnvironment :execrows
DELETE FROM secret_value_occurrences
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteSecretValueOccurrencesForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeleteSecretValueOccurrencesForEnvironment(ctx context.Context, arg DeleteSecretValueOccurrencesForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecretValueOccurrencesForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSnapshotEntriesForEnvironment = `-- name: DeleteSnapshotEntriesForEnvironment :execrows
DELETE FROM snapshot_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteSnapshotEntriesForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeleteSnapshotEntriesForEnvironment(ctx context.Context, arg DeleteSnapshotEntriesForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnapshotEntriesForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSnapshotsForEnvironment = `-- name: DeleteSnapshotsForEnvironment :execrows
DELETE FROM snapshots
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteSnapshotsForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) DeleteSnapshotsForEnvironment(ctx context.Context, arg DeleteSnapshotsForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnapshotsForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, org_id, project_id, environment_id, revision, schema_revision,
       published_by, published_at, payload_present, collected_at, collected_policy
FROM snapshots
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
ORDER BY revision DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

// GetLatestSnapshot is the delivery-shaped read: a workload fetch defaults to
// the latest published snapshot for its (project, environment).
func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Revision,
		&i.SchemaRevision,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.PayloadPresent,
		&i.CollectedAt,
		&i.CollectedPolicy,
	)
	return i, err
}

const getRevisionPinForWorkload = `-- name: GetRevisionPinForWorkload :one
SELECT id, org_id, project_id, environment_id, workload_principal_id,
       snapshot_id, revision, authority_principal_id, expires_at, created_at,
       authorized_at, history_authorized, schema_override
FROM revision_pins
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
  AND workload_principal_id = $4
`

type GetRevisionPinForWorkloadParams struct {
	ChainOrgID          string
	ChainProjectID      string
	ChainEnvID          string
	WorkloadPrincipalID string
}

func (q *Queries) GetRevisionPinForWorkload(ctx context.Context, arg GetRevisionPinForWorkloadParams) (RevisionPin, error) {
	row := q.db.QueryRow(ctx, getRevisionPinForWorkload,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.WorkloadPrincipalID,
	)
	var i RevisionPin
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.WorkloadPrincipalID,
		&i.SnapshotID,
		&i.Revision,
		&i.AuthorityPrincipalID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AuthorizedAt,
		&i.HistoryAuthorized,
		&i.SchemaOverride,
	)
	return i, err
}

const getSnapshotByRevision = `-- name: GetSnapshotByRevision :one
SELECT id, org_id, project_id, environment_id, revision, schema_revision,
       published_by, published_at, payload_present, collected_at, collected_policy
FROM snapshots
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND revision = $4
`

type GetSnapshotByRevisionParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	Revision       int64
}

func (q *Queries) GetSnapshotByRevision(ctx context.Context, arg GetSnapshotByRevisionParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByRevision,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.Revision,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Revision,
		&i.SchemaRevision,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.PayloadPresent,
		&i.CollectedAt,
		&i.CollectedPolicy,
	)
	return i, err
}

const insertPendingChange = `-- name: InsertPendingChange :exec

INSERT INTO pending_changes (
    id, org_id, project_id, environment_id, key_id, owner_id,
    operation, ciphertext, staged_from_revision, staged_from_entry, created_at, source, secret, material_secret
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14
)
`

type InsertPendingChangeParams struct {
	ID                 string
	ChainOrgID         string
	ChainProjectID     string
	ChainEnvID         string
	KeyID              string
	OwnerID            string
	Operation          string
	Ciphertext         []byte
	StagedFromRevision int64
	StagedFromEntry    string
	CreatedAt          pgtype.Timestamptz
	Source             string
	Secret             bool
	MaterialSecret     bool
}

// Revisions, drafts and publishing (#51). Tenant-scoped statements: the
// reserved chain_* parameters are bound by the store's binding layer from
// proof fields only - never from caller arguments; the SQL predicate analyzer
// enforces the conjunct shape.
//
// `environment_id` is an ordinary column on all four tables (see the
// migration), and every environment-addressed statement below binds it from
// the proof's resolved chain - spelled `chain_env_id`, the same reserved name
// values.sql uses. The project-scoped statements are the ones that must span
// environments: publish reads the publisher's whole working state across the
// project before it knows which environments it touches, the matrix signals
// are a project-wide question, and a key delete cascades across every
// environment at once.
func (q *Queries) InsertPendingChange(ctx context.Context, arg InsertPendingChangeParams) error {
	_, err := q.db.Exec(ctx, insertPendingChange,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.KeyID,
		arg.OwnerID,
		arg.Operation,
		arg.Ciphertext,
		arg.StagedFromRevision,
		arg.StagedFromEntry,
		arg.CreatedAt,
		arg.Source,
		arg.Secret,
		arg.MaterialSecret,
	)
	return err
}

const insertRevisionKeyChange = `-- name: InsertRevisionKeyChange :exec
INSERT INTO revision_key_changes (
    org_id, project_id, environment_id, revision, key_id, key_name, change
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type InsertRevisionKeyChangeParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	Revision       int64
	KeyID          string
	KeyName        string
	Change         string
}

func (q *Queries) InsertRevisionKeyChange(ctx context.Context, arg InsertRevisionKeyChangeParams) error {
	_, err := q.db.Exec(ctx, insertRevisionKeyChange,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.Revision,
		arg.KeyID,
		arg.KeyName,
		arg.Change,
	)
	return err
}

const insertRevisionPin = `-- name: InsertRevisionPin :exec
INSERT INTO revision_pins (
    id, org_id, project_id, environment_id, workload_principal_id,
    snapshot_id, revision, authority_principal_id, expires_at, created_at,
    authorized_at, history_authorized, schema_override
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13
)
`

type InsertRevisionPinParams struct {
	ID                   string
	ChainOrgID           string
	ChainProjectID       string
	ChainEnvID           string
	WorkloadPrincipalID  string
	SnapshotID           string
	Revision             int64
	AuthorityPrincipalID string
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	AuthorizedAt         pgtype.Timestamptz
	HistoryAuthorized    bool
	SchemaOverride       bool
}

func (q *Queries) InsertRevisionPin(ctx context.Context, arg InsertRevisionPinParams) error {
	_, err := q.db.Exec(ctx, insertRevisionPin,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.WorkloadPrincipalID,
		arg.SnapshotID,
		arg.Revision,
		arg.AuthorityPrincipalID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.AuthorizedAt,
		arg.HistoryAuthorized,
		arg.SchemaOverride,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (
    id, org_id, project_id, environment_id, revision,
    schema_revision, published_by, published_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type InsertSnapshotParams struct {
	ID             string
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	Revision       int64
	SchemaRevision int64
	PublishedBy    string
	PublishedAt    pgtype.Timestamptz
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.Revision,
		arg.SchemaRevision,
		arg.PublishedBy,
		arg.PublishedAt,
	)
	return err
}

const insertSnapshotEntry = `-- name: InsertSnapshotEntry :exec
INSERT INTO snapshot_entries (
    id, org_id, project_id, environment_id, snapshot_id,
    key_id, key_name, classification, ciphertext, value_entry_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
`

type InsertSnapshotEntryParams struct {
	ID             string
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	SnapshotID     string
	KeyID          string
	KeyName        string
	Classification string
	Ciphertext     []byte
	ValueEntryID   string
}

func (q *Queries) InsertSnapshotEntry(ctx context.Context, arg InsertSnapshotEntryParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotEntry,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.SnapshotID,
		arg.KeyID,
		arg.KeyName,
		arg.Classification,
		arg.Ciphertext,
		arg.ValueEntryID,
	)
	return err
}

const listPendingChangesForOwner = `-- name: ListPendingChangesForOwner :many
SELECT id, org_id, project_id, environment_id, key_id, owner_id,
       operation, ciphertext, staged_from_revision, staged_from_entry, created_at, source, secret, material_secret
FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND owner_id = $3
ORDER BY environment_id, key_id
`

type ListPendingChangesForOwnerParams struct {
	ChainOrgID     string
	ChainProjectID string
	OwnerID        string
}

// ListPendingChangesForOwner is the publish path's read: a publish carries
// ONLY the publisher's own pending changes, so the query that returns draft
// material is keyed on the owner and there is no statement that hands one
// principal another's ciphertext.
func (q *Queries) ListPendingChangesForOwner(ctx context.Context, arg ListPendingChangesForOwnerParams) ([]PendingChange, error) {
	rows, err := q.db.Query(ctx, listPendingChangesForOwner, arg.ChainOrgID, arg.ChainProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingChange
	for rows.Next() {
		var i PendingChange
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.OwnerID,
			&i.Operation,
			&i.Ciphertext,
			&i.StagedFromRevision,
			&i.StagedFromEntry,
			&i.CreatedAt,
			&i.Source,
			&i.Secret,
			&i.MaterialSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingChangesForOwnerInEnvironment = `-- name: ListPendingChangesForOwnerInEnvironment :many
SELECT id, org_id, project_id, environment_id, key_id, owner_id,
       operation, ciphertext, staged_from_revision, staged_from_entry, created_at, source, secret, material_secret
FROM pending_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND owner_id = $4
ORDER BY key_id
`

type ListPendingChangesForOwnerInEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	OwnerID        string
}

// ListPendingChangesForOwnerInEnvironment is the preview read. Owner and
// environment are both predicates in SQL, so the preview cannot hand one
// principal another's ciphertext or material from another environment.
func (q *Queries) ListPendingChangesForOwnerInEnvironment(ctx context.Context, arg ListPendingChangesForOwnerInEnvironmentParams) ([]PendingChange, error) {
	rows, err := q.db.Query(ctx, listPendingChangesForOwnerInEnvironment,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.OwnerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingChange
	for rows.Next() {
		var i PendingChange
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.OwnerID,
			&i.Operation,
			&i.Ciphertext,
			&i.StagedFromRevision,
			&i.StagedFromEntry,
			&i.CreatedAt,
			&i.Source,
			&i.Secret,
			&i.MaterialSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMarkers = `-- name: ListPendingMarkers :many
SELECT id, environment_id, key_id, owner_id, operation
FROM pending_changes
WHERE org_id = $1 AND project_id = $2
ORDER BY environment_id, key_id, owner_id
`

type ListPendingMarkersParams struct {
	ChainOrgID     string
	ChainProjectID string
}

type ListPendingMarkersRow struct {
	ID            string
	EnvironmentID string
	KeyID         string
	OwnerID       string
	Operation     string
}

// ListPendingMarkers is the matrix signal's read and the group-closure
// collision check's read. It returns NO ciphertext: what another principal's
// draft may disclose is write-presence and nothing else, and the cheapest way
// to hold that rule is a statement that cannot carry the material.
func (q *Queries) ListPendingMarkers(ctx context.Context, arg ListPendingMarkersParams) ([]ListPendingMarkersRow, error) {
	rows, err := q.db.Query(ctx, listPendingMarkers, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMarkersRow
	for rows.Next() {
		var i ListPendingMarkersRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.OwnerID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionKeyChanges = `-- name: ListRevisionKeyChanges :many
SELECT org_id, project_id, environment_id, revision, key_id, key_name, change
FROM revision_key_changes
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND revision = $4
ORDER BY key_name
`

type ListRevisionKeyChangesParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	Revision       int64
}

func (q *Queries) ListRevisionKeyChanges(ctx context.Context, arg ListRevisionKeyChangesParams) ([]RevisionKeyChange, error) {
	rows, err := q.db.Query(ctx, listRevisionKeyChanges,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.Revision,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionKeyChange
	for rows.Next() {
		var i RevisionKeyChange
		if err := rows.Scan(
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Revision,
			&i.KeyID,
			&i.KeyName,
			&i.Change,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionPins = `-- name: ListRevisionPins :many
SELECT id, org_id, project_id, environment_id, workload_principal_id,
       snapshot_id, revision, authority_principal_id, expires_at, created_at,
       authorized_at, history_authorized, schema_override
FROM revision_pins
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
ORDER BY workload_principal_id
`

type ListRevisionPinsParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) ListRevisionPins(ctx context.Context, arg ListRevisionPinsParams) ([]RevisionPin, error) {
	rows, err := q.db.Query(ctx, listRevisionPins, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionPin
	for rows.Next() {
		var i RevisionPin
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.WorkloadPrincipalID,
			&i.SnapshotID,
			&i.Revision,
			&i.AuthorityPrincipalID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AuthorizedAt,
			&i.HistoryAuthorized,
			&i.SchemaOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretValueOccurrenceIDs = `-- name: ListSecretValueOccurrenceIDs :many
SELECT value_entry_id
FROM secret_value_occurrences
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
ORDER BY value_entry_id
`

type ListSecretValueOccurrenceIDsParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) ListSecretValueOccurrenceIDs(ctx context.Context, arg ListSecretValueOccurrenceIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSecretValueOccurrenceIDs, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var value_entry_id string
		if err := rows.Scan(&value_entry_id); err != nil {
			return nil, err
		}
		items = append(items, value_entry_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotEntries = `-- name: ListSnapshotEntries :many
SELECT id, org_id, project_id, environment_id, snapshot_id,
       key_id, key_name, classification, ciphertext, value_entry_id
FROM snapshot_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND snapshot_id = $4
ORDER BY key_name
`

type ListSnapshotEntriesParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	SnapshotID     string
}

func (q *Queries) ListSnapshotEntries(ctx context.Context, arg ListSnapshotEntriesParams) ([]SnapshotEntry, error) {
	rows, err := q.db.Query(ctx, listSnapshotEntries,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.SnapshotID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotEntry
	for rows.Next() {
		var i SnapshotEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SnapshotID,
			&i.KeyID,
			&i.KeyName,
			&i.Classification,
			&i.Ciphertext,
			&i.ValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, org_id, project_id, environment_id, revision, schema_revision,
       published_by, published_at, payload_present, collected_at, collected_policy
FROM snapshots
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
ORDER BY revision DESC
`

type ListSnapshotsParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Revision,
			&i.SchemaRevision,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.PayloadPresent,
			&i.CollectedAt,
			&i.CollectedPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSnapshotRevisions = `-- name: ProjectSnapshotRevisions :many
SELECT environment_id, revision FROM snapshots
WHERE org_id = $1 AND project_id = $2
`

type ProjectSnapshotRevisionsParams struct {
	ChainOrgID     string
	ChainProjectID string
}

type ProjectSnapshotRevisionsRow struct {
	EnvironmentID string
	Revision      int64
}

// ProjectSnapshotRevisions returns the project-confined revision rows used to
// build the definitions plan/apply pin (#70). The repository folds the maximum
// per environment; keeping aggregation out of SQL leaves the chain predicate in
// the conservative analyzer's provable shape.
func (q *Queries) ProjectSnapshotRevisions(ctx context.Context, arg ProjectSnapshotRevisionsParams) ([]ProjectSnapshotRevisionsRow, error) {
	rows, err := q.db.Query(ctx, projectSnapshotRevisions, arg.ChainOrgID, arg.ChainProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSnapshotRevisionsRow
	for rows.Next() {
		var i ProjectSnapshotRevisionsRow
		if err := rows.Scan(&i.EnvironmentID, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSecretValueOccurrence = `-- name: RecordSecretValueOccurrence :exec
INSERT INTO secret_value_occurrences (
    value_entry_id, org_id, project_id, environment_id
) VALUES (
    $1, $2,
    $3, $4
)
`

type RecordSecretValueOccurrenceParams struct {
	ValueEntryID   string
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

func (q *Queries) RecordSecretValueOccurrence(ctx context.Context, arg RecordSecretValueOccurrenceParams) error {
	_, err := q.db.Exec(ctx, recordSecretValueOccurrence,
		arg.ValueEntryID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
	)
	return err
}
