// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: values.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteValueEntriesForEnvironment = `-- name: DeleteValueEntriesForEnvironment :execrows
DELETE FROM value_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
`

type DeleteValueEntriesForEnvironmentParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

// DeleteValueEntriesForEnvironment cascades an environment's whole set out
// when the environment itself is deleted: the values cannot outlive the only
// thing they attach to, and the composite foreign key would refuse the delete
// while they existed.
func (q *Queries) DeleteValueEntriesForEnvironment(ctx context.Context, arg DeleteValueEntriesForEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteValueEntriesForEnvironment, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteValueEntry = `-- name: DeleteValueEntry :execrows
DELETE FROM value_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND key_id = $4
`

type DeleteValueEntryParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	KeyID          string
}

func (q *Queries) DeleteValueEntry(ctx context.Context, arg DeleteValueEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteValueEntry,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.KeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getValueEntry = `-- name: GetValueEntry :one

SELECT id, org_id, project_id, environment_id, key_id, ciphertext, updated_at, updated_by
FROM value_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3 AND key_id = $4
`

type GetValueEntryParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	KeyID          string
}

// The flat value model (#50). Tenant-scoped statements: the reserved chain_*
// parameters are bound by the store's binding layer from proof fields only -
// never from caller arguments; the SQL predicate analyzer enforces the
// conjunct shape.
//
// `environment_id` is an ordinary column here rather than a chain column (see
// the migration): every environment-addressed statement below still binds it
// from the proof's resolved chain — spelled `chain_env_id`, the same reserved
// name environments.sql uses for the row it addresses — and the two
// project-scoped statements at the bottom are the ones that must span
// environments.
//
// There is no UPDATE. A value write is delete-then-insert with a FRESH row id,
// because the row id is bound into the ciphertext's AAD and an id bound into
// an AAD is immutable and never reused (encryption-model ADR).
func (q *Queries) GetValueEntry(ctx context.Context, arg GetValueEntryParams) (ValueEntry, error) {
	row := q.db.QueryRow(ctx, getValueEntry,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.KeyID,
	)
	var i ValueEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.KeyID,
		&i.Ciphertext,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertValueEntry = `-- name: InsertValueEntry :exec
INSERT INTO value_entries (
    id, org_id, project_id, environment_id, key_id, ciphertext, updated_at, updated_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type InsertValueEntryParams struct {
	ID             string
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
	KeyID          string
	Ciphertext     []byte
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      string
}

func (q *Queries) InsertValueEntry(ctx context.Context, arg InsertValueEntryParams) error {
	_, err := q.db.Exec(ctx, insertValueEntry,
		arg.ID,
		arg.ChainOrgID,
		arg.ChainProjectID,
		arg.ChainEnvID,
		arg.KeyID,
		arg.Ciphertext,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const listValueEntries = `-- name: ListValueEntries :many
SELECT id, org_id, project_id, environment_id, key_id, ciphertext, updated_at, updated_by
FROM value_entries
WHERE org_id = $1 AND project_id = $2
  AND environment_id = $3
ORDER BY key_id
`

type ListValueEntriesParams struct {
	ChainOrgID     string
	ChainProjectID string
	ChainEnvID     string
}

// ListValueEntries is the delivery-shaped read: one environment's entire set,
// which is exactly what "a `set` entry delivers, `absent` delivers nothing"
// means when absence is the absence of a row.
func (q *Queries) ListValueEntries(ctx context.Context, arg ListValueEntriesParams) ([]ValueEntry, error) {
	rows, err := q.db.Query(ctx, listValueEntries, arg.ChainOrgID, arg.ChainProjectID, arg.ChainEnvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValueEntry
	for rows.Next() {
		var i ValueEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.Ciphertext,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValueEnvironmentsForKey = `-- name: ListValueEnvironmentsForKey :many
SELECT environment_id FROM value_entries
WHERE org_id = $1 AND project_id = $2
  AND key_id = $3
ORDER BY environment_id
`

type ListValueEnvironmentsForKeyParams struct {
	ChainOrgID     string
	ChainProjectID string
	KeyID          string
}

// ListValueEnvironmentsForKey spans the project's environments deliberately:
// it is the input to the key-delete refusal, which must be able to NAME the
// environments that still deliver material for the key.
func (q *Queries) ListValueEnvironmentsForKey(ctx context.Context, arg ListValueEnvironmentsForKeyParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listValueEnvironmentsForKey, arg.ChainOrgID, arg.ChainProjectID, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var environment_id string
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
