// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const auditWatermark = `-- name: AuditWatermark :one

SELECT 9223372036854775807 AS watermark
`

// The settled-transaction watermark: every row whose txid is strictly below
// it belongs to a transaction that has finished, so paging under it cannot
// skip a row that commits later (postgres allocates seq before commit).
// This engine's single write connection makes allocation order and commit
// order identical, so the maximum sentinel admits every visible row.
// wenv:instance-scoped
func (q *Queries) AuditWatermark(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, auditWatermark)
	var watermark int64
	err := row.Scan(&watermark)
	return watermark, err
}

const insertInstanceAuditEvent = `-- name: InsertInstanceAuditEvent :exec
INSERT INTO audit_instance_events (
    id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInstanceAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

func (q *Queries) InsertInstanceAuditEvent(ctx context.Context, arg InsertInstanceAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertInstanceAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.RecordedAt,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec

INSERT INTO audit_tenant_events (
    id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTenantAuditEventParams struct {
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ScopeClass        string
	OrgID             string
	ProjectID         sql.NullString
	EnvID             sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

// Audit trails (#45): the application layer holds INSERT and SELECT only on
// both audit tables - the append-only CI invariant scans this file. Chain
// parameters are bound by the store's binding layer (and, for the denial
// writer, by the authorization package's enumerated surface) from resolved
// chains only - never from caller arguments.
//
// Page order is seq (allocation order); the cursor is `seq > ?`. Timestamps
// are fixed-width UTC microsecond text on this engine, so recorded_at range
// predicates compare correctly.
func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.Type,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.OccurredAsserted,
		arg.RecordedAt,
		arg.ActorID,
		arg.ActorClass,
		arg.ActorCredentialID,
		arg.AuthorityID,
		arg.ScopeClass,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Outcome,
		arg.CorrelationID,
		arg.SourceIp,
		arg.UserAgent,
		arg.Origin,
		arg.Payload,
	)
	return err
}

const pageInstanceAudit = `-- name: PageInstanceAudit :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_instance_events
WHERE seq > ? AND txid < ? AND recorded_at >= ? AND recorded_at <= ?
ORDER BY seq LIMIT ?
`

type PageInstanceAuditParams struct {
	Seq          int64
	Txid         int64
	RecordedAt   string
	RecordedAt_2 string
	Limit        int64
}

func (q *Queries) PageInstanceAudit(ctx context.Context, arg PageInstanceAuditParams) ([]AuditInstanceEvent, error) {
	rows, err := q.db.QueryContext(ctx, pageInstanceAudit,
		arg.Seq,
		arg.Txid,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditInstanceEvent
	for rows.Next() {
		var i AuditInstanceEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditEnv = `-- name: PageTenantAuditEnv :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = ? AND project_id = ? AND env_id = ? AND seq > ? AND txid < ? AND recorded_at >= ? AND recorded_at <= ?
ORDER BY seq LIMIT ?
`

type PageTenantAuditEnvParams struct {
	OrgID        string
	ProjectID    sql.NullString
	EnvID        sql.NullString
	Seq          int64
	Txid         int64
	RecordedAt   string
	RecordedAt_2 string
	Limit        int64
}

func (q *Queries) PageTenantAuditEnv(ctx context.Context, arg PageTenantAuditEnvParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.QueryContext(ctx, pageTenantAuditEnv,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.Seq,
		arg.Txid,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditOrg = `-- name: PageTenantAuditOrg :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = ? AND seq > ? AND txid < ? AND recorded_at >= ? AND recorded_at <= ?
ORDER BY seq LIMIT ?
`

type PageTenantAuditOrgParams struct {
	OrgID        string
	Seq          int64
	Txid         int64
	RecordedAt   string
	RecordedAt_2 string
	Limit        int64
}

func (q *Queries) PageTenantAuditOrg(ctx context.Context, arg PageTenantAuditOrgParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.QueryContext(ctx, pageTenantAuditOrg,
		arg.OrgID,
		arg.Seq,
		arg.Txid,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageTenantAuditProject = `-- name: PageTenantAuditProject :many
SELECT seq, txid, id, type, schema_version, occurred_at, occurred_asserted, recorded_at,
    actor_id, actor_class, actor_credential_id, authority_id,
    scope_class, org_id, project_id, env_id,
    object_type, object_id, outcome, correlation_id,
    source_ip, user_agent, origin, payload
FROM audit_tenant_events
WHERE org_id = ? AND project_id = ? AND seq > ? AND txid < ? AND recorded_at >= ? AND recorded_at <= ?
ORDER BY seq LIMIT ?
`

type PageTenantAuditProjectParams struct {
	OrgID        string
	ProjectID    sql.NullString
	Seq          int64
	Txid         int64
	RecordedAt   string
	RecordedAt_2 string
	Limit        int64
}

func (q *Queries) PageTenantAuditProject(ctx context.Context, arg PageTenantAuditProjectParams) ([]AuditTenantEvent, error) {
	rows, err := q.db.QueryContext(ctx, pageTenantAuditProject,
		arg.OrgID,
		arg.ProjectID,
		arg.Seq,
		arg.Txid,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTenantEvent
	for rows.Next() {
		var i AuditTenantEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Txid,
			&i.ID,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.OccurredAsserted,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorClass,
			&i.ActorCredentialID,
			&i.AuthorityID,
			&i.ScopeClass,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Outcome,
			&i.CorrelationID,
			&i.SourceIp,
			&i.UserAgent,
			&i.Origin,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
