// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authn.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const advancePrincipalGeneration = `-- name: AdvancePrincipalGeneration :exec
UPDATE principals SET session_generation = session_generation + 1 WHERE id = ?
`

// wenv:authn-resolution
func (q *Queries) AdvancePrincipalGeneration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, advancePrincipalGeneration, id)
	return err
}

const advanceTOTPStep = `-- name: AdvanceTOTPStep :execrows
UPDATE totp_credentials SET last_step = ?, row_version = row_version + 1
WHERE id = ? AND row_version = ? AND last_step < ?
`

type AdvanceTOTPStepParams struct {
	LastStep   int64
	ID         string
	RowVersion int64
	LastStep_2 int64
}

// Single-use per (account, step): a code is consumed only if its step is
// strictly beyond the last one, which the CAS enforces atomically.
// wenv:authn-resolution
func (q *Queries) AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceTOTPStep,
		arg.LastStep,
		arg.ID,
		arg.RowVersion,
		arg.LastStep_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const confirmTOTP = `-- name: ConfirmTOTP :execrows
UPDATE totp_credentials
SET confirmed_at = ?, last_step = ?, row_version = row_version + 1
WHERE id = ? AND row_version = ? AND confirmed_at IS NULL AND last_step < ?
`

type ConfirmTOTPParams struct {
	ConfirmedAt sql.NullString
	LastStep    int64
	ID          string
	RowVersion  int64
	LastStep_2  int64
}

// Confirmation is the account-security mutation's write: it promotes the
// pending seed and consumes the confirming step in one CAS.
// wenv:authn-resolution
func (q *Queries) ConfirmTOTP(ctx context.Context, arg ConfirmTOTPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, confirmTOTP,
		arg.ConfirmedAt,
		arg.LastStep,
		arg.ID,
		arg.RowVersion,
		arg.LastStep_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeCredentialAuthority = `-- name: ConsumeCredentialAuthority :execrows
UPDATE credential_authorities SET consumed_at = ?
WHERE id = ? AND consumed_at IS NULL
`

type ConsumeCredentialAuthorityParams struct {
	ConsumedAt sql.NullString
	ID         string
}

// Single-use consumption: the NULL guard is the atomic claim, so two
// concurrent presentations cannot both establish a credential.
// wenv:authn-resolution
func (q *Queries) ConsumeCredentialAuthority(ctx context.Context, arg ConsumeCredentialAuthorityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeCredentialAuthority, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeOutstandingAuthoritiesForAccount = `-- name: ConsumeOutstandingAuthoritiesForAccount :exec
UPDATE credential_authorities SET consumed_at = ?
WHERE account_id = ? AND consumed_at IS NULL
`

type ConsumeOutstandingAuthoritiesForAccountParams struct {
	ConsumedAt sql.NullString
	AccountID  string
}

// Minting an establishment authority for an account consumes every other
// outstanding one, so a second live reset token cannot linger past the point
// the operator believes the flow completed.
// wenv:authn-resolution
func (q *Queries) ConsumeOutstandingAuthoritiesForAccount(ctx context.Context, arg ConsumeOutstandingAuthoritiesForAccountParams) error {
	_, err := q.db.ExecContext(ctx, consumeOutstandingAuthoritiesForAccount, arg.ConsumedAt, arg.AccountID)
	return err
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

// wenv:authn-resolution
func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingTOTPForAccount = `-- name: DeletePendingTOTPForAccount :exec
DELETE FROM totp_credentials WHERE account_id = ? AND confirmed_at IS NULL
`

// wenv:authn-resolution
func (q *Queries) DeletePendingTOTPForAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deletePendingTOTPForAccount, accountID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

// wenv:authn-resolution
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForPrincipal = `-- name: DeleteSessionsForPrincipal :exec
DELETE FROM sessions WHERE principal_id = ?
`

// Every session of the principal dies, atomically and without reaching the
// client  -  the invalidation that token rotation structurally cannot do.
// wenv:authn-resolution
func (q *Queries) DeleteSessionsForPrincipal(ctx context.Context, principalID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForPrincipal, principalID)
	return err
}

const deleteTOTPForAccount = `-- name: DeleteTOTPForAccount :exec
DELETE FROM totp_credentials WHERE account_id = ?
`

// wenv:authn-resolution
func (q *Queries) DeleteTOTPForAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteTOTPForAccount, accountID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, principal_id, username, display_name, created_at FROM accounts
WHERE id = ?
`

// wenv:authn-resolution
func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, principal_id, username, display_name, created_at FROM accounts
WHERE username = ?
`

// wenv:authn-resolution
func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getConfirmedTOTPForAccount = `-- name: GetConfirmedTOTPForAccount :one

SELECT id, account_id, seed, dek_version, credential_epoch, row_version,
       last_step, created_step, confirmed_at, created_at
FROM totp_credentials WHERE account_id = ? AND confirmed_at IS NOT NULL
`

// Factors (#54, human-auth ADR). TOTP, recovery codes and the session-rotation
// writers join the enumerated resolution surface for the same reason the login
// writers did: they mutate the artifacts that decide how strongly a caller
// authenticated, which is resolved rather than authorized.
// wenv:authn-resolution
func (q *Queries) GetConfirmedTOTPForAccount(ctx context.Context, accountID string) (TotpCredential, error) {
	row := q.db.QueryRowContext(ctx, getConfirmedTOTPForAccount, accountID)
	var i TotpCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seed,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.LastStep,
		&i.CreatedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialAuthorityByVerifier = `-- name: GetCredentialAuthorityByVerifier :one
SELECT id, account_id, purpose, issued_by, credential_epoch, expires_at,
       consumed_at, created_at
FROM credential_authorities WHERE verifier = ?
`

type GetCredentialAuthorityByVerifierRow struct {
	ID              string
	AccountID       string
	Purpose         string
	IssuedBy        string
	CredentialEpoch int64
	ExpiresAt       string
	ConsumedAt      sql.NullString
	CreatedAt       string
}

// wenv:authn-resolution
func (q *Queries) GetCredentialAuthorityByVerifier(ctx context.Context, verifier []byte) (GetCredentialAuthorityByVerifierRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialAuthorityByVerifier, verifier)
	var i GetCredentialAuthorityByVerifierRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.IssuedBy,
		&i.CredentialEpoch,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialEpoch = `-- name: GetCredentialEpoch :one

SELECT credential_epoch FROM auth_instance_state WHERE id = 1
`

// Human authentication (#47, human-auth ADR). These live in the resolution
// surface for the same reason chain resolution does: deciding WHO a caller is
// cannot run under a proof, because the proof is what the answer produces.
// The write paths below are enumerated and pinned; anything else that mutates
// inside this surface fails the sole-writer analyzer.
// wenv:authn-resolution
func (q *Queries) GetCredentialEpoch(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCredentialEpoch)
	var credential_epoch int64
	err := row.Scan(&credential_epoch)
	return credential_epoch, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT account_id, verifier, kdf_memory_kib, kdf_time, kdf_parallelism,
       dek_version, credential_epoch, row_version, updated_at
FROM password_credentials WHERE account_id = ?
`

// wenv:authn-resolution
func (q *Queries) GetPasswordCredential(ctx context.Context, accountID string) (PasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredential, accountID)
	var i PasswordCredential
	err := row.Scan(
		&i.AccountID,
		&i.Verifier,
		&i.KdfMemoryKib,
		&i.KdfTime,
		&i.KdfParallelism,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTOTPForAccount = `-- name: GetPendingTOTPForAccount :one
SELECT id, account_id, seed, dek_version, credential_epoch, row_version,
       last_step, created_step, confirmed_at, created_at
FROM totp_credentials WHERE account_id = ? AND confirmed_at IS NULL
`

// wenv:authn-resolution
func (q *Queries) GetPendingTOTPForAccount(ctx context.Context, accountID string) (TotpCredential, error) {
	row := q.db.QueryRowContext(ctx, getPendingTOTPForAccount, accountID)
	var i TotpCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seed,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.LastStep,
		&i.CreatedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipalGeneration = `-- name: GetPrincipalGeneration :one
SELECT session_generation FROM principals WHERE id = ?
`

// wenv:authn-resolution
func (q *Queries) GetPrincipalGeneration(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalGeneration, id)
	var session_generation int64
	err := row.Scan(&session_generation)
	return session_generation, err
}

const getPrincipalKind = `-- name: GetPrincipalKind :one

SELECT kind FROM principals WHERE id = ?
`

// The denial writer's actor-class lookup (#45, audit-model ADR amendment
// part 4): the flush transaction resolves the denied principal's kind for
// the event's actor class. Runs only inside authn.WriteDenial.
// wenv:authn-resolution
func (q *Queries) GetPrincipalKind(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getRecoveryCodes = `-- name: GetRecoveryCodes :one
SELECT account_id, batch, dek_version, credential_epoch, row_version, generated_at
FROM recovery_codes WHERE account_id = ?
`

// wenv:authn-resolution
func (q *Queries) GetRecoveryCodes(ctx context.Context, accountID string) (RecoveryCode, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryCodes, accountID)
	var i RecoveryCode
	err := row.Scan(
		&i.AccountID,
		&i.Batch,
		&i.DekVersion,
		&i.CredentialEpoch,
		&i.RowVersion,
		&i.GeneratedAt,
	)
	return i, err
}

const getSessionByVerifier = `-- name: GetSessionByVerifier :one
SELECT id, principal_id, artifact, session_generation, credential_epoch,
       auth_method, factors, authenticated_at, ceremony_id, created_at,
       last_seen_at, idle_expires_at, absolute_expires_at
FROM sessions WHERE verifier = ?
`

type GetSessionByVerifierRow struct {
	ID                string
	PrincipalID       string
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   string
	CeremonyID        sql.NullString
	CreatedAt         string
	LastSeenAt        string
	IdleExpiresAt     string
	AbsoluteExpiresAt string
}

// wenv:authn-resolution
func (q *Queries) GetSessionByVerifier(ctx context.Context, verifier []byte) (GetSessionByVerifierRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByVerifier, verifier)
	var i GetSessionByVerifierRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Artifact,
		&i.SessionGeneration,
		&i.CredentialEpoch,
		&i.AuthMethod,
		&i.Factors,
		&i.AuthenticatedAt,
		&i.CeremonyID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, principal_id, username, display_name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertAccountParams struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   string
}

// wenv:authn-resolution
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.PrincipalID,
		arg.Username,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const insertCredentialAuthority = `-- name: InsertCredentialAuthority :exec
INSERT INTO credential_authorities
    (id, verifier, account_id, purpose, issued_by, credential_epoch, expires_at, consumed_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NULL, ?)
`

type InsertCredentialAuthorityParams struct {
	ID              string
	Verifier        []byte
	AccountID       string
	Purpose         string
	IssuedBy        string
	CredentialEpoch int64
	ExpiresAt       string
	CreatedAt       string
}

// wenv:authn-resolution
func (q *Queries) InsertCredentialAuthority(ctx context.Context, arg InsertCredentialAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, insertCredentialAuthority,
		arg.ID,
		arg.Verifier,
		arg.AccountID,
		arg.Purpose,
		arg.IssuedBy,
		arg.CredentialEpoch,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO grants (id, principal_id, capability, org_id, project_id, env_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertGrantParams struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       sql.NullString
	ProjectID   sql.NullString
	EnvID       sql.NullString
	CreatedAt   string
}

// wenv:authn-resolution
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertGrant,
		arg.ID,
		arg.PrincipalID,
		arg.Capability,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvID,
		arg.CreatedAt,
	)
	return err
}

const insertPasswordCredential = `-- name: InsertPasswordCredential :exec
INSERT INTO password_credentials
    (account_id, verifier, kdf_memory_kib, kdf_time, kdf_parallelism,
     dek_version, credential_epoch, row_version, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)
`

type InsertPasswordCredentialParams struct {
	AccountID       string
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	UpdatedAt       string
}

// wenv:authn-resolution
func (q *Queries) InsertPasswordCredential(ctx context.Context, arg InsertPasswordCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertPasswordCredential,
		arg.AccountID,
		arg.Verifier,
		arg.KdfMemoryKib,
		arg.KdfTime,
		arg.KdfParallelism,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.UpdatedAt,
	)
	return err
}

const insertPrincipal = `-- name: InsertPrincipal :exec

INSERT INTO principals (id, kind, created_at, session_generation)
VALUES (?, ?, ?, 1)
`

type InsertPrincipalParams struct {
	ID        string
	Kind      string
	CreatedAt string
}

// Enumerated writers.
// wenv:authn-resolution
func (q *Queries) InsertPrincipal(ctx context.Context, arg InsertPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, insertPrincipal, arg.ID, arg.Kind, arg.CreatedAt)
	return err
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec
INSERT INTO recovery_codes
    (account_id, batch, dek_version, credential_epoch, row_version, generated_at)
VALUES (?, ?, ?, ?, 1, ?)
`

type InsertRecoveryCodesParams struct {
	AccountID       string
	Batch           []byte
	DekVersion      int64
	CredentialEpoch int64
	GeneratedAt     string
}

// wenv:authn-resolution
func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryCodes,
		arg.AccountID,
		arg.Batch,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.GeneratedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions
    (id, principal_id, verifier, artifact, session_generation, credential_epoch,
     auth_method, factors, authenticated_at, ceremony_id, created_at,
     last_seen_at, idle_expires_at, absolute_expires_at, source_ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID                string
	PrincipalID       string
	Verifier          []byte
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   string
	CeremonyID        sql.NullString
	CreatedAt         string
	LastSeenAt        string
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	SourceIp          string
	UserAgent         string
}

// wenv:authn-resolution
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.PrincipalID,
		arg.Verifier,
		arg.Artifact,
		arg.SessionGeneration,
		arg.CredentialEpoch,
		arg.AuthMethod,
		arg.Factors,
		arg.AuthenticatedAt,
		arg.CeremonyID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.SourceIp,
		arg.UserAgent,
	)
	return err
}

const insertTOTP = `-- name: InsertTOTP :exec
INSERT INTO totp_credentials
    (id, account_id, seed, dek_version, credential_epoch, row_version,
     last_step, created_step, confirmed_at, created_at)
VALUES (?, ?, ?, ?, ?, 1, ?, ?, NULL, ?)
`

type InsertTOTPParams struct {
	ID              string
	AccountID       string
	Seed            []byte
	DekVersion      int64
	CredentialEpoch int64
	LastStep        int64
	CreatedStep     int64
	CreatedAt       string
}

// wenv:authn-resolution
func (q *Queries) InsertTOTP(ctx context.Context, arg InsertTOTPParams) error {
	_, err := q.db.ExecContext(ctx, insertTOTP,
		arg.ID,
		arg.AccountID,
		arg.Seed,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.LastStep,
		arg.CreatedStep,
		arg.CreatedAt,
	)
	return err
}

const listGrantsForPrincipal = `-- name: ListGrantsForPrincipal :many
SELECT capability, org_id, project_id, env_id FROM grants
WHERE principal_id = ?
`

type ListGrantsForPrincipalRow struct {
	Capability string
	OrgID      sql.NullString
	ProjectID  sql.NullString
	EnvID      sql.NullString
}

// wenv:authn-resolution
func (q *Queries) ListGrantsForPrincipal(ctx context.Context, principalID string) ([]ListGrantsForPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForPrincipalRow
	for rows.Next() {
		var i ListGrantsForPrincipalRow
		if err := rows.Scan(
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEnvChain = `-- name: ResolveEnvChain :one
SELECT org_id, project_id, id FROM environments
WHERE org_id = ? AND project_id = ? AND id = ?
`

type ResolveEnvChainParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

type ResolveEnvChainRow struct {
	OrgID     string
	ProjectID string
	ID        string
}

// wenv:authn-resolution
func (q *Queries) ResolveEnvChain(ctx context.Context, arg ResolveEnvChainParams) (ResolveEnvChainRow, error) {
	row := q.db.QueryRowContext(ctx, resolveEnvChain, arg.OrgID, arg.ProjectID, arg.ID)
	var i ResolveEnvChainRow
	err := row.Scan(&i.OrgID, &i.ProjectID, &i.ID)
	return i, err
}

const resolveOrgChain = `-- name: ResolveOrgChain :one


SELECT id FROM orgs WHERE id = ?
`

// The authorization package's enumerated resolution surface (tenant-isolation
// ADR bootstrap carve-out): the only statements that read chain tables with
// request-supplied identifiers, because authorize() runs them to mint the
// proof everything else requires. Each is annotated and content-pinned in the
// allowlist fixture - drift fails the build until re-reviewed.
// Chain resolution is one query, one round trip, regardless of which level
// is missing: the denormalized chain columns plus composite ancestry FKs make
// the addressed row's own chain authoritative, so no per-level walk exists.
// wenv:authn-resolution
func (q *Queries) ResolveOrgChain(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveOrgChain, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const resolveProjectChain = `-- name: ResolveProjectChain :one
SELECT org_id, id FROM projects WHERE org_id = ? AND id = ?
`

type ResolveProjectChainParams struct {
	OrgID string
	ID    string
}

type ResolveProjectChainRow struct {
	OrgID string
	ID    string
}

// wenv:authn-resolution
func (q *Queries) ResolveProjectChain(ctx context.Context, arg ResolveProjectChainParams) (ResolveProjectChainRow, error) {
	row := q.db.QueryRowContext(ctx, resolveProjectChain, arg.OrgID, arg.ID)
	var i ResolveProjectChainRow
	err := row.Scan(&i.OrgID, &i.ID)
	return i, err
}

const rotateSessionFactors = `-- name: RotateSessionFactors :exec
UPDATE sessions SET verifier = ?, factors = ? WHERE id = ?
`

type RotateSessionFactorsParams struct {
	Verifier []byte
	Factors  string
	ID       string
}

// Step-up rotates the session token and rewrites its factor set; the original
// authenticated_at and ceremony_id are preserved so absolute-age attribution
// cannot be reset by repeated step-ups.
// wenv:authn-resolution
func (q *Queries) RotateSessionFactors(ctx context.Context, arg RotateSessionFactorsParams) error {
	_, err := q.db.ExecContext(ctx, rotateSessionFactors, arg.Verifier, arg.Factors, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ?, idle_expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt    string
	IdleExpiresAt string
	ID            string
}

// wenv:authn-resolution
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.IdleExpiresAt, arg.ID)
	return err
}

const updatePasswordCredentialCAS = `-- name: UpdatePasswordCredentialCAS :execrows
UPDATE password_credentials
SET verifier = ?, kdf_memory_kib = ?, kdf_time = ?, kdf_parallelism = ?,
    dek_version = ?, credential_epoch = ?, row_version = row_version + 1,
    updated_at = ?
WHERE account_id = ? AND row_version = ?
`

type UpdatePasswordCredentialCASParams struct {
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	UpdatedAt       string
	AccountID       string
	RowVersion      int64
}

// Compare-and-swap on row_version: a resumable, lock-free `reencrypt` racing
// a password reset would otherwise write the stale verifier back under the
// new DEK version and silently resurrect a superseded password.
// wenv:authn-resolution
func (q *Queries) UpdatePasswordCredentialCAS(ctx context.Context, arg UpdatePasswordCredentialCASParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePasswordCredentialCAS,
		arg.Verifier,
		arg.KdfMemoryKib,
		arg.KdfTime,
		arg.KdfParallelism,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.UpdatedAt,
		arg.AccountID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRecoveryCodesCAS = `-- name: UpdateRecoveryCodesCAS :execrows
UPDATE recovery_codes
SET batch = ?, dek_version = ?, credential_epoch = ?,
    row_version = row_version + 1, generated_at = ?
WHERE account_id = ? AND row_version = ?
`

type UpdateRecoveryCodesCASParams struct {
	Batch           []byte
	DekVersion      int64
	CredentialEpoch int64
	GeneratedAt     string
	AccountID       string
	RowVersion      int64
}

// Regeneration and consumption both rewrite the batch under a CAS, so a
// concurrent second presentation of the same code loses and fails closed.
// wenv:authn-resolution
func (q *Queries) UpdateRecoveryCodesCAS(ctx context.Context, arg UpdateRecoveryCodesCASParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRecoveryCodesCAS,
		arg.Batch,
		arg.DekVersion,
		arg.CredentialEpoch,
		arg.GeneratedAt,
		arg.AccountID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
