// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authn.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const getPrincipalKind = `-- name: GetPrincipalKind :one

SELECT kind FROM principals WHERE id = ?
`

// The denial writer's actor-class lookup (#45, audit-model ADR amendment
// part 4): the flush transaction resolves the denied principal's kind for
// the event's actor class. Runs only inside authn.WriteDenial.
// wenv:authn-resolution
func (q *Queries) GetPrincipalKind(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const listGrantsForPrincipal = `-- name: ListGrantsForPrincipal :many
SELECT capability, org_id, project_id, env_id FROM grants
WHERE principal_id = ?
`

type ListGrantsForPrincipalRow struct {
	Capability string
	OrgID      sql.NullString
	ProjectID  sql.NullString
	EnvID      sql.NullString
}

// wenv:authn-resolution
func (q *Queries) ListGrantsForPrincipal(ctx context.Context, principalID string) ([]ListGrantsForPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForPrincipalRow
	for rows.Next() {
		var i ListGrantsForPrincipalRow
		if err := rows.Scan(
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEnvChain = `-- name: ResolveEnvChain :one
SELECT org_id, project_id, id FROM environments
WHERE org_id = ? AND project_id = ? AND id = ?
`

type ResolveEnvChainParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

type ResolveEnvChainRow struct {
	OrgID     string
	ProjectID string
	ID        string
}

// wenv:authn-resolution
func (q *Queries) ResolveEnvChain(ctx context.Context, arg ResolveEnvChainParams) (ResolveEnvChainRow, error) {
	row := q.db.QueryRowContext(ctx, resolveEnvChain, arg.OrgID, arg.ProjectID, arg.ID)
	var i ResolveEnvChainRow
	err := row.Scan(&i.OrgID, &i.ProjectID, &i.ID)
	return i, err
}

const resolveOrgChain = `-- name: ResolveOrgChain :one


SELECT id FROM orgs WHERE id = ?
`

// The authorization package's enumerated resolution surface (tenant-isolation
// ADR bootstrap carve-out): the only statements that read chain tables with
// request-supplied identifiers, because authorize() runs them to mint the
// proof everything else requires. Each is annotated and content-pinned in the
// allowlist fixture - drift fails the build until re-reviewed.
// Chain resolution is one query, one round trip, regardless of which level
// is missing: the denormalized chain columns plus composite ancestry FKs make
// the addressed row's own chain authoritative, so no per-level walk exists.
// wenv:authn-resolution
func (q *Queries) ResolveOrgChain(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveOrgChain, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const resolveProjectChain = `-- name: ResolveProjectChain :one
SELECT org_id, id FROM projects WHERE org_id = ? AND id = ?
`

type ResolveProjectChainParams struct {
	OrgID string
	ID    string
}

type ResolveProjectChainRow struct {
	OrgID string
	ID    string
}

// wenv:authn-resolution
func (q *Queries) ResolveProjectChain(ctx context.Context, arg ResolveProjectChainParams) (ResolveProjectChainRow, error) {
	row := q.db.QueryRowContext(ctx, resolveProjectChain, arg.OrgID, arg.ID)
	var i ResolveProjectChainRow
	err := row.Scan(&i.OrgID, &i.ID)
	return i, err
}
