// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlitegen

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :exec

INSERT INTO environments (id, org_id, project_id, name, note, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEnvironmentParams struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	Note      string
	CreatedAt string
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, createEnvironment,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, org_id, project_id, name, note, created_at FROM environments
WHERE org_id = ? AND project_id = ? AND id = ?
`

type GetEnvironmentParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, arg.OrgID, arg.ProjectID, arg.ID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const updateEnvironmentNote = `-- name: UpdateEnvironmentNote :execrows
UPDATE environments SET note = ?
WHERE org_id = ? AND project_id = ? AND id = ?
`

type UpdateEnvironmentNoteParams struct {
	Note      string
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) UpdateEnvironmentNote(ctx context.Context, arg UpdateEnvironmentNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEnvironmentNote,
		arg.Note,
		arg.OrgID,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
