// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlitegen

import (
	"context"
)

const createFolder = `-- name: CreateFolder :exec

INSERT INTO folders (id, org_id, project_id, path, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateFolderParams struct {
	ID        string
	OrgID     string
	ProjectID string
	Path      string
	CreatedAt string
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
//
// A folder is addressed WITHIN the project the proof resolved: the chain
// conjuncts come from the proof, and `id` is an ordinary caller argument like
// `path` is. The scope lattice has no folder level (permission-model ADR: no
// folder-scoped grants), so there is no chain field for it to bind from - and
// it needs none: a folder id from another project simply misses the chain
// predicate, which is the uniform nonexistent outcome.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) error {
	_, err := q.db.ExecContext(ctx, createFolder,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Path,
		arg.CreatedAt,
	)
	return err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders WHERE org_id = ? AND project_id = ? AND id = ?
`

type DeleteFolderParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFolder, arg.OrgID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFolder = `-- name: GetFolder :one
SELECT id, org_id, project_id, path, created_at FROM folders
WHERE org_id = ? AND project_id = ? AND id = ?
`

type GetFolderParams struct {
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, arg.OrgID, arg.ProjectID, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, org_id, project_id, path, created_at FROM folders
WHERE org_id = ? AND project_id = ? ORDER BY path
`

type ListFoldersParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameFolder = `-- name: RenameFolder :execrows
UPDATE folders SET path = ?
WHERE org_id = ? AND project_id = ? AND id = ?
`

type RenameFolderParams struct {
	Path      string
	OrgID     string
	ProjectID string
	ID        string
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameFolder,
		arg.Path,
		arg.OrgID,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
