// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyring.sql

package sqlitegen

import (
	"context"
)

const acquireHierarchyGeneration = `-- name: AcquireHierarchyGeneration :one
SELECT generation FROM key_generations WHERE scope = 'hierarchy'
`

func (q *Queries) AcquireHierarchyGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, acquireHierarchyGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getActiveMasterKey = `-- name: GetActiveMasterKey :one
SELECT version, root_key_epoch, state, blob, created_at
FROM master_keys WHERE state = 'active'
`

func (q *Queries) GetActiveMasterKey(ctx context.Context) (MasterKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveMasterKey)
	var i MasterKey
	err := row.Scan(
		&i.Version,
		&i.RootKeyEpoch,
		&i.State,
		&i.Blob,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveTier3Key = `-- name: GetActiveTier3Key :one
SELECT id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at
FROM tier3_keys WHERE purpose = ? AND org_id = ? AND project_id = ? AND state = 'active'
`

type GetActiveTier3KeyParams struct {
	Purpose   string
	OrgID     string
	ProjectID string
}

func (q *Queries) GetActiveTier3Key(ctx context.Context, arg GetActiveTier3KeyParams) (Tier3Key, error) {
	row := q.db.QueryRowContext(ctx, getActiveTier3Key, arg.Purpose, arg.OrgID, arg.ProjectID)
	var i Tier3Key
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.OrgID,
		&i.ProjectID,
		&i.Version,
		&i.MasterKeyVersion,
		&i.State,
		&i.Blob,
		&i.CreatedAt,
	)
	return i, err
}

const insertKeyGeneration = `-- name: InsertKeyGeneration :exec
INSERT INTO key_generations (scope, generation) VALUES (?, 1)
`

func (q *Queries) InsertKeyGeneration(ctx context.Context, scope string) error {
	_, err := q.db.ExecContext(ctx, insertKeyGeneration, scope)
	return err
}

const insertMasterKey = `-- name: InsertMasterKey :exec
INSERT INTO master_keys (version, root_key_epoch, state, blob, created_at)
VALUES (?, ?, 'active', ?, ?)
`

type InsertMasterKeyParams struct {
	Version      int64
	RootKeyEpoch int64
	Blob         []byte
	CreatedAt    string
}

func (q *Queries) InsertMasterKey(ctx context.Context, arg InsertMasterKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertMasterKey,
		arg.Version,
		arg.RootKeyEpoch,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}

const insertTier3Key = `-- name: InsertTier3Key :exec
INSERT INTO tier3_keys (id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at)
VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?)
`

type InsertTier3KeyParams struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	Blob             []byte
	CreatedAt        string
}

func (q *Queries) InsertTier3Key(ctx context.Context, arg InsertTier3KeyParams) error {
	_, err := q.db.ExecContext(ctx, insertTier3Key,
		arg.ID,
		arg.Purpose,
		arg.OrgID,
		arg.ProjectID,
		arg.Version,
		arg.MasterKeyVersion,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}
