// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyring.sql

package sqlitegen

import (
	"context"
)

const acquireHierarchyGeneration = `-- name: AcquireHierarchyGeneration :one
SELECT generation FROM key_generations WHERE scope = 'hierarchy'
`

func (q *Queries) AcquireHierarchyGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, acquireHierarchyGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getActiveMasterKeys = `-- name: GetActiveMasterKeys :many
SELECT version, root_key_epoch, state, blob, created_at
FROM master_keys WHERE state = 'active' ORDER BY root_key_epoch DESC
`

func (q *Queries) GetActiveMasterKeys(ctx context.Context) ([]MasterKey, error) {
	rows, err := q.db.QueryContext(ctx, getActiveMasterKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterKey
	for rows.Next() {
		var i MasterKey
		if err := rows.Scan(
			&i.Version,
			&i.RootKeyEpoch,
			&i.State,
			&i.Blob,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTier3Key = `-- name: GetActiveTier3Key :one
SELECT id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at
FROM tier3_keys WHERE purpose = ? AND org_id = ? AND project_id = ? AND state = 'active'
`

type GetActiveTier3KeyParams struct {
	Purpose   string
	OrgID     string
	ProjectID string
}

func (q *Queries) GetActiveTier3Key(ctx context.Context, arg GetActiveTier3KeyParams) (Tier3Key, error) {
	row := q.db.QueryRowContext(ctx, getActiveTier3Key, arg.Purpose, arg.OrgID, arg.ProjectID)
	var i Tier3Key
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.OrgID,
		&i.ProjectID,
		&i.Version,
		&i.MasterKeyVersion,
		&i.State,
		&i.Blob,
		&i.CreatedAt,
	)
	return i, err
}

const insertKeyGeneration = `-- name: InsertKeyGeneration :exec
INSERT INTO key_generations (scope, generation) VALUES (?, 1)
`

func (q *Queries) InsertKeyGeneration(ctx context.Context, scope string) error {
	_, err := q.db.ExecContext(ctx, insertKeyGeneration, scope)
	return err
}

const insertMasterKey = `-- name: InsertMasterKey :exec
INSERT INTO master_keys (version, root_key_epoch, state, blob, created_at)
VALUES (?, ?, 'active', ?, ?)
`

type InsertMasterKeyParams struct {
	Version      int64
	RootKeyEpoch int64
	Blob         []byte
	CreatedAt    string
}

func (q *Queries) InsertMasterKey(ctx context.Context, arg InsertMasterKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertMasterKey,
		arg.Version,
		arg.RootKeyEpoch,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}

const insertTier3Key = `-- name: InsertTier3Key :exec
INSERT INTO tier3_keys (id, purpose, org_id, project_id, version, master_key_version, state, blob, created_at)
VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?)
`

type InsertTier3KeyParams struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	Blob             []byte
	CreatedAt        string
}

func (q *Queries) InsertTier3Key(ctx context.Context, arg InsertTier3KeyParams) error {
	_, err := q.db.ExecContext(ctx, insertTier3Key,
		arg.ID,
		arg.Purpose,
		arg.OrgID,
		arg.ProjectID,
		arg.Version,
		arg.MasterKeyVersion,
		arg.Blob,
		arg.CreatedAt,
	)
	return err
}

const retireTier3Key = `-- name: RetireTier3Key :execrows
UPDATE tier3_keys SET state = 'retired'
WHERE purpose = ? AND org_id = ? AND project_id = ? AND state = 'active'
`

type RetireTier3KeyParams struct {
	Purpose   string
	OrgID     string
	ProjectID string
}

// RetireTier3Key retires the active key for one scope so a rotation can put a
// new version in its place. It is an UPDATE rather than a delete: the
// superseded row's blob is what still opens material written under it, and the
// one-active-per-scope index is what makes the swap unambiguous.
func (q *Queries) RetireTier3Key(ctx context.Context, arg RetireTier3KeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireTier3Key, arg.Purpose, arg.OrgID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireTier3KeyAtVersion = `-- name: RetireTier3KeyAtVersion :execrows
UPDATE tier3_keys SET state = 'retired'
WHERE purpose = ? AND org_id = ? AND project_id = ? AND state = 'active'
  AND version = ?
`

type RetireTier3KeyAtVersionParams struct {
	Purpose   string
	OrgID     string
	ProjectID string
	Version   int64
}

// RetireTier3KeyAtVersion is RetireTier3Key as a compare-and-swap: it retires
// the active key only when it is still the version the caller prepared its
// successor against. Zero rows means a concurrent rotation won -- the caller
// must refuse, not stack a second successor on the wrong predecessor.
func (q *Queries) RetireTier3KeyAtVersion(ctx context.Context, arg RetireTier3KeyAtVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireTier3KeyAtVersion,
		arg.Purpose,
		arg.OrgID,
		arg.ProjectID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
