// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"database/sql"
)

type Account struct {
	ID                 string
	PrincipalID        string
	Username           string
	DisplayName        string
	CreatedAt          string
	WebauthnUserHandle []byte
}

type AuditInstanceEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

type AuditTenantEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ScopeClass        string
	OrgID             string
	ProjectID         sql.NullString
	EnvID             sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

type AuthInstanceState struct {
	ID              int64
	CredentialEpoch int64
	UpdatedAt       string
	RestoreEpoch    int64
	ReactivatedAt   sql.NullString
}

type CredentialAuthority struct {
	ID                        string
	Verifier                  []byte
	AccountID                 string
	Purpose                   string
	IssuedBy                  string
	EstablishedCredentialKind string
	CredentialEpoch           int64
	ExpiresAt                 string
	ConsumedAt                sql.NullString
	CreatedAt                 string
}

type CredentialPolicy struct {
	ID                       int64
	MaxFiniteLifetimeSeconds int64
	AllowIndefinite          int64
	MaxLiveCredentials       int64
	UpdatedAt                sql.NullString
	UpdatedBy                sql.NullString
}

type Environment struct {
	ID                  string
	OrgID               string
	ProjectID           string
	Name                string
	Note                string
	CreatedAt           string
	DisplayOrder        int64
	Protected           int64
	ReauthWindowSeconds sql.NullInt64
}

type ExternalIdentity struct {
	ID              string
	AccountID       string
	Kind            string
	Issuer          string
	Subject         string
	ProviderID      string
	CredentialEpoch int64
	CreatedAt       string
}

type FederationIssuer struct {
	ID               string
	Issuer           string
	IssuerType       string
	JwksMode         string
	StaticJwks       sql.NullString
	RefusedAudiences string
	CreatedAt        string
	CreatedBy        string
	UpdatedAt        sql.NullString
	UpdatedBy        sql.NullString
}

type Folder struct {
	ID        string
	OrgID     string
	ProjectID string
	Path      string
	CreatedAt string
}

type Grant struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       sql.NullString
	ProjectID   sql.NullString
	EnvID       sql.NullString
	CreatedAt   string
}

type GrantOrigin struct {
	ID        string
	GrantID   string
	Kind      string
	Subject   string
	CreatedAt string
}

type Key struct {
	ID              string
	OrgID           string
	ProjectID       string
	Name            string
	FolderPath      string
	Classification  string
	Description     string
	Deprecated      int64
	DeprecationNote string
	Declaration     string
	RequiredMode    string
	ForbiddenMode   string
	GroupID         sql.NullString
	CreatedAt       string
}

type KeyGeneration struct {
	Scope      string
	Generation int64
}

type KeyGroup struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	CreatedAt string
}

type KeyPresenceEnvironment struct {
	OrgID         string
	ProjectID     string
	KeyID         string
	EnvironmentID string
	Rule          string
}

type MachineCredential struct {
	ID               string
	ServiceAccountID string
	Kind             string
	Verifier         []byte
	PrefixHint       sql.NullString
	Lifetime         string
	ExpiresAt        sql.NullString
	CredentialEpoch  int64
	CreatedAt        string
	CreatedBy        string
	RevokedAt        sql.NullString
	LastUsedAt       sql.NullString
	IssuerID         sql.NullString
	Subject          sql.NullString
	Audience         sql.NullString
	RequiredClaims   sql.NullString
	ReactivatedAt    sql.NullString
}

type MasterKey struct {
	Version      int64
	RootKeyEpoch int64
	State        string
	Blob         []byte
	CreatedAt    string
}

type OidcProvider struct {
	ID              string
	Slug            string
	DisplayName     string
	Kind            string
	Issuer          string
	ClientID        string
	ClientSecret    []byte
	Scopes          string
	RedirectUri     string
	JitPolicy       sql.NullString
	AssurancePolicy sql.NullString
	Enabled         int64
	DekVersion      int64
	RowVersion      int64
	CreatedAt       string
	UpdatedAt       string
}

type OidcTransaction struct {
	ID                     string
	StateVerifier          []byte
	Nonce                  []byte
	PkceVerifier           string
	ProviderID             string
	Issuer                 string
	RedirectUri            string
	Purpose                string
	BindingKind            string
	InitiatingSessionID    sql.NullString
	BrowserBindingVerifier []byte
	AccountID              sql.NullString
	EnvironmentID          sql.NullString
	CeremonyID             sql.NullString
	CredentialEpoch        int64
	CreatedAt              string
	ExpiresAt              string
	ConsumedAt             sql.NullString
}

type Org struct {
	ID        string
	Name      string
	Active    int64
	Metadata  string
	CreatedAt string
}

type PasswordCredential struct {
	AccountID       string
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	RowVersion      int64
	UpdatedAt       string
}

type PinGeneration struct {
	PrincipalID   string
	EnvironmentID string
	Generation    int64
}

type Principal struct {
	ID                string
	Kind              string
	CreatedAt         string
	SessionGeneration int64
	Class             sql.NullString
	ReconciledEpoch   int64
}

type Project struct {
	ID        string
	OrgID     string
	Name      string
	CreatedAt string
}

type ProjectSchemaRevision struct {
	OrgID     string
	ProjectID string
	Revision  int64
}

type ReauthWindow struct {
	ID              string
	SessionID       string
	EnvironmentID   string
	CeremonyID      string
	FactorClass     string
	SingleDecision  int64
	AuthenticatedAt string
	WindowExpiresAt string
	HardExpiresAt   string
	CredentialEpoch int64
	ConsumedAt      sql.NullString
	CreatedAt       string
}

type RecoveryCode struct {
	AccountID       string
	Batch           []byte
	DekVersion      int64
	CredentialEpoch int64
	RowVersion      int64
	GeneratedAt     string
}

type SamlProvider struct {
	ID                              string
	Slug                            string
	DisplayName                     string
	Kind                            string
	EntityID                        string
	AcsUrl                          string
	SsoRedirectUrl                  string
	SigningCertificates             []byte
	AssurancePolicy                 sql.NullString
	AllowEmailNameid                int64
	ForceSignRequests               int64
	MetadataWantAuthnRequestsSigned int64
	MetadataSource                  string
	MetadataUrl                     sql.NullString
	MetadataSigned                  int64
	MetadataSigningFingerprint      sql.NullString
	MetadataValidUntil              sql.NullString
	Enabled                         int64
	RowVersion                      int64
	CreatedAt                       string
	UpdatedAt                       string
}

type SamlReplay struct {
	Issuer      string
	AssertionID string
	ExpiresAt   string
	CreatedAt   string
}

type SamlSpKey struct {
	ID                  string
	State               string
	EncryptedPrivateKey []byte
	CertificateDer      []byte
	Fingerprint         string
	DekVersion          int64
	RowVersion          int64
	CreatedAt           string
}

type SamlTransaction struct {
	ID                  string
	RequestID           string
	RelayStateVerifier  []byte
	InitiatorVerifier   []byte
	ProviderID          string
	EntityID            string
	AcsUrl              string
	Purpose             string
	InitiatingSessionID sql.NullString
	AccountID           sql.NullString
	EnvironmentID       sql.NullString
	CeremonyID          sql.NullString
	CredentialEpoch     int64
	CreatedAt           string
	ExpiresAt           string
	ConsumedAt          sql.NullString
}

type ServiceAccount struct {
	ID          string
	PrincipalID string
	OrgID       string
	ProjectID   string
	Name        string
	Kind        string
	CreatedAt   string
	CreatedBy   string
}

type Session struct {
	ID                string
	PrincipalID       string
	Verifier          []byte
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   string
	CeremonyID        sql.NullString
	CreatedAt         string
	LastSeenAt        string
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	SourceIp          string
	UserAgent         string
	CsrfVerifier      []byte
	ProviderID        sql.NullString
	SamlProviderID    sql.NullString
}

type Tier3Key struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	State            string
	Blob             []byte
	CreatedAt        string
}

type TotpChallenge struct {
	ID               string
	AccountID        string
	SessionID        sql.NullString
	Purpose          string
	OperationBinding sql.NullString
	EnvironmentID    sql.NullString
	CredentialEpoch  int64
	ExpiresAt        string
	ConsumedAt       sql.NullString
	CreatedAt        string
}

type TotpCredential struct {
	ID              string
	AccountID       string
	Seed            []byte
	DekVersion      int64
	CredentialEpoch int64
	RowVersion      int64
	LastStep        int64
	CreatedStep     int64
	ConfirmedAt     sql.NullString
	CreatedAt       string
}

type ValueEntry struct {
	ID            string
	OrgID         string
	ProjectID     string
	EnvironmentID string
	KeyID         string
	Ciphertext    []byte
	UpdatedAt     string
	UpdatedBy     string
}

type WebauthnCeremony struct {
	ID                string
	ChallengeVerifier []byte
	SessionData       []byte
	AccountID         sql.NullString
	SessionID         sql.NullString
	Purpose           string
	OperationBinding  sql.NullString
	EnvironmentID     sql.NullString
	CredentialID      sql.NullString
	CredentialEpoch   int64
	ExpiresAt         string
	ConsumedAt        sql.NullString
	CreatedAt         string
}

type WebauthnCredential struct {
	ID              string
	AccountID       string
	CredentialID    []byte
	PublicKey       []byte
	Aaguid          []byte
	SignCount       int64
	Transports      string
	Discoverable    int64
	BackupEligible  int64
	BackupState     int64
	Label           string
	CredentialEpoch int64
	RowVersion      int64
	DisabledAt      sql.NullString
	CreatedAt       string
	LastUsedAt      sql.NullString
}
