// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"database/sql"
)

type Account struct {
	ID          string
	PrincipalID string
	Username    string
	DisplayName string
	CreatedAt   string
}

type AuditInstanceEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

type AuditTenantEvent struct {
	Seq               int64
	ID                string
	Type              string
	SchemaVersion     int64
	OccurredAt        string
	OccurredAsserted  int64
	RecordedAt        string
	ActorID           sql.NullString
	ActorClass        string
	ActorCredentialID sql.NullString
	AuthorityID       sql.NullString
	ScopeClass        string
	OrgID             string
	ProjectID         sql.NullString
	EnvID             sql.NullString
	ObjectType        sql.NullString
	ObjectID          sql.NullString
	Outcome           string
	CorrelationID     sql.NullString
	SourceIp          sql.NullString
	UserAgent         sql.NullString
	Origin            string
	Payload           string
}

type AuthInstanceState struct {
	ID              int64
	CredentialEpoch int64
	UpdatedAt       string
}

type CredentialAuthority struct {
	ID              string
	Verifier        []byte
	AccountID       string
	Purpose         string
	IssuedBy        string
	CredentialEpoch int64
	ExpiresAt       string
	ConsumedAt      sql.NullString
	CreatedAt       string
}

type Environment struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	Note      string
	CreatedAt string
}

type Grant struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       sql.NullString
	ProjectID   sql.NullString
	EnvID       sql.NullString
	CreatedAt   string
}

type KeyGeneration struct {
	Scope      string
	Generation int64
}

type MasterKey struct {
	Version      int64
	RootKeyEpoch int64
	State        string
	Blob         []byte
	CreatedAt    string
}

type Org struct {
	ID        string
	Name      string
	Active    int64
	Metadata  string
	CreatedAt string
}

type PasswordCredential struct {
	AccountID       string
	Verifier        []byte
	KdfMemoryKib    int64
	KdfTime         int64
	KdfParallelism  int64
	DekVersion      int64
	CredentialEpoch int64
	RowVersion      int64
	UpdatedAt       string
}

type Principal struct {
	ID                string
	Kind              string
	CreatedAt         string
	SessionGeneration int64
}

type Project struct {
	ID        string
	OrgID     string
	Name      string
	CreatedAt string
}

type Session struct {
	ID                string
	PrincipalID       string
	Verifier          []byte
	Artifact          string
	SessionGeneration int64
	CredentialEpoch   int64
	AuthMethod        string
	Factors           string
	AuthenticatedAt   string
	CeremonyID        sql.NullString
	CreatedAt         string
	LastSeenAt        string
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	SourceIp          string
	UserAgent         string
}

type Tier3Key struct {
	ID               string
	Purpose          string
	OrgID            string
	ProjectID        string
	Version          int64
	MasterKeyVersion int64
	State            string
	Blob             []byte
	CreatedAt        string
}
