// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlitegen

import (
	"context"
)

const createProject = `-- name: CreateProject :exec

INSERT INTO projects (id, org_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID        string
	OrgID     string
	Name      string
	CreatedAt string
}

// Tenant-scoped statements. The reserved chain_* parameters are bound by the
// store's binding layer from proof fields only - never from caller
// arguments; the SQL predicate analyzer enforces the conjunct shape.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}
