// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package sqlitegen

import (
	"context"
)

const deletePendingChangeByID = `-- name: DeletePendingChangeByID :execrows
DELETE FROM pending_changes
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND id = ?
`

type DeletePendingChangeByIDParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	ID            string
}

func (q *Queries) DeletePendingChangeByID(ctx context.Context, arg DeletePendingChangeByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingChangeByID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingChangeForCell = `-- name: DeletePendingChangeForCell :execrows
DELETE FROM pending_changes
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND key_id = ? AND owner_id = ?
`

type DeletePendingChangeForCellParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	KeyID         string
	OwnerID       string
}

// DeletePendingChangeForCell collects the superseded version. Editing a cell
// mints a new version id rather than mutating the old row, and the old row is
// removed in the same transaction: only the latest version per (owner, key,
// environment) is publishable, so keeping the predecessor would store draft
// material nothing may ever publish.
func (q *Queries) DeletePendingChangeForCell(ctx context.Context, arg DeletePendingChangeForCellParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingChangeForCell,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.KeyID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingChangesForEnvironment = `-- name: DeletePendingChangesForEnvironment :execrows
DELETE FROM pending_changes
WHERE org_id = ? AND project_id = ? AND environment_id = ?
`

type DeletePendingChangesForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) DeletePendingChangesForEnvironment(ctx context.Context, arg DeletePendingChangesForEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingChangesForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingChangesForKey = `-- name: DeletePendingChangesForKey :execrows
DELETE FROM pending_changes
WHERE org_id = ? AND project_id = ? AND key_id = ?
`

type DeletePendingChangesForKeyParams struct {
	OrgID     string
	ProjectID string
	KeyID     string
}

// DeletePendingChangesForKey is the key-delete cascade: deleting a key
// invalidates every pending change referencing it, so a publish naming one of
// those versions is refused loudly instead of resurrecting a key the schema no
// longer declares.
func (q *Queries) DeletePendingChangesForKey(ctx context.Context, arg DeletePendingChangesForKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingChangesForKey, arg.OrgID, arg.ProjectID, arg.KeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRevisionKeyChangesForEnvironment = `-- name: DeleteRevisionKeyChangesForEnvironment :execrows
DELETE FROM revision_key_changes
WHERE org_id = ? AND project_id = ? AND environment_id = ?
`

type DeleteRevisionKeyChangesForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) DeleteRevisionKeyChangesForEnvironment(ctx context.Context, arg DeleteRevisionKeyChangesForEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRevisionKeyChangesForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSnapshotEntriesForEnvironment = `-- name: DeleteSnapshotEntriesForEnvironment :execrows
DELETE FROM snapshot_entries
WHERE org_id = ? AND project_id = ? AND environment_id = ?
`

type DeleteSnapshotEntriesForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) DeleteSnapshotEntriesForEnvironment(ctx context.Context, arg DeleteSnapshotEntriesForEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSnapshotEntriesForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSnapshotsForEnvironment = `-- name: DeleteSnapshotsForEnvironment :execrows
DELETE FROM snapshots
WHERE org_id = ? AND project_id = ? AND environment_id = ?
`

type DeleteSnapshotsForEnvironmentParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) DeleteSnapshotsForEnvironment(ctx context.Context, arg DeleteSnapshotsForEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSnapshotsForEnvironment, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, org_id, project_id, environment_id, revision, schema_revision, published_by, published_at
FROM snapshots
WHERE org_id = ? AND project_id = ? AND environment_id = ?
ORDER BY revision DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

// GetLatestSnapshot is the delivery-shaped read: a workload fetch defaults to
// the latest published snapshot for its (project, environment).
func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Revision,
		&i.SchemaRevision,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getSnapshotByRevision = `-- name: GetSnapshotByRevision :one
SELECT id, org_id, project_id, environment_id, revision, schema_revision, published_by, published_at
FROM snapshots
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND revision = ?
`

type GetSnapshotByRevisionParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	Revision      int64
}

func (q *Queries) GetSnapshotByRevision(ctx context.Context, arg GetSnapshotByRevisionParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByRevision,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Revision,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Revision,
		&i.SchemaRevision,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const insertPendingChange = `-- name: InsertPendingChange :exec

INSERT INTO pending_changes (
    id, org_id, project_id, environment_id, key_id, owner_id,
    operation, ciphertext, staged_from_revision, staged_from_entry, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPendingChangeParams struct {
	ID                 string
	OrgID              string
	ProjectID          string
	EnvironmentID      string
	KeyID              string
	OwnerID            string
	Operation          string
	Ciphertext         []byte
	StagedFromRevision int64
	StagedFromEntry    string
	CreatedAt          string
}

// Revisions, drafts and publishing (#51). Tenant-scoped statements: the
// reserved chain parameters are bound by the store's binding layer from proof
// fields only - never from caller arguments; the SQL predicate analyzer
// enforces the conjunct shape.
//
// `environment_id` is an ordinary column on all four tables (see the
// migration), and every environment-addressed statement below binds it from
// the proof's resolved chain. The project-scoped statements are the ones that
// must span environments: publish reads the publisher's whole working state
// across the project before it knows which environments it touches, the matrix
// signals are a project-wide question, and a key delete cascades across every
// environment at once.
func (q *Queries) InsertPendingChange(ctx context.Context, arg InsertPendingChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertPendingChange,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.KeyID,
		arg.OwnerID,
		arg.Operation,
		arg.Ciphertext,
		arg.StagedFromRevision,
		arg.StagedFromEntry,
		arg.CreatedAt,
	)
	return err
}

const insertRevisionKeyChange = `-- name: InsertRevisionKeyChange :exec
INSERT INTO revision_key_changes (
    org_id, project_id, environment_id, revision, key_id, key_name, change
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertRevisionKeyChangeParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	Revision      int64
	KeyID         string
	KeyName       string
	Change        string
}

func (q *Queries) InsertRevisionKeyChange(ctx context.Context, arg InsertRevisionKeyChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertRevisionKeyChange,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Revision,
		arg.KeyID,
		arg.KeyName,
		arg.Change,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (
    id, org_id, project_id, environment_id, revision,
    schema_revision, published_by, published_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSnapshotParams struct {
	ID             string
	OrgID          string
	ProjectID      string
	EnvironmentID  string
	Revision       int64
	SchemaRevision int64
	PublishedBy    string
	PublishedAt    string
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Revision,
		arg.SchemaRevision,
		arg.PublishedBy,
		arg.PublishedAt,
	)
	return err
}

const insertSnapshotEntry = `-- name: InsertSnapshotEntry :exec
INSERT INTO snapshot_entries (
    id, org_id, project_id, environment_id, snapshot_id,
    key_id, key_name, classification, ciphertext, value_entry_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSnapshotEntryParams struct {
	ID             string
	OrgID          string
	ProjectID      string
	EnvironmentID  string
	SnapshotID     string
	KeyID          string
	KeyName        string
	Classification string
	Ciphertext     []byte
	ValueEntryID   string
}

func (q *Queries) InsertSnapshotEntry(ctx context.Context, arg InsertSnapshotEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshotEntry,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SnapshotID,
		arg.KeyID,
		arg.KeyName,
		arg.Classification,
		arg.Ciphertext,
		arg.ValueEntryID,
	)
	return err
}

const listPendingChangesForOwner = `-- name: ListPendingChangesForOwner :many
SELECT id, org_id, project_id, environment_id, key_id, owner_id,
       operation, ciphertext, staged_from_revision, staged_from_entry, created_at
FROM pending_changes
WHERE org_id = ? AND project_id = ? AND owner_id = ?
ORDER BY environment_id, key_id
`

type ListPendingChangesForOwnerParams struct {
	OrgID     string
	ProjectID string
	OwnerID   string
}

// ListPendingChangesForOwner is the publish path's read: a publish carries
// ONLY the publisher's own pending changes, so the query that returns draft
// material is keyed on the owner and there is no statement that hands one
// principal another's ciphertext.
func (q *Queries) ListPendingChangesForOwner(ctx context.Context, arg ListPendingChangesForOwnerParams) ([]PendingChange, error) {
	rows, err := q.db.QueryContext(ctx, listPendingChangesForOwner, arg.OrgID, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingChange
	for rows.Next() {
		var i PendingChange
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.OwnerID,
			&i.Operation,
			&i.Ciphertext,
			&i.StagedFromRevision,
			&i.StagedFromEntry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMarkers = `-- name: ListPendingMarkers :many
SELECT id, environment_id, key_id, owner_id, operation
FROM pending_changes
WHERE org_id = ? AND project_id = ?
ORDER BY environment_id, key_id, owner_id
`

type ListPendingMarkersParams struct {
	OrgID     string
	ProjectID string
}

type ListPendingMarkersRow struct {
	ID            string
	EnvironmentID string
	KeyID         string
	OwnerID       string
	Operation     string
}

// ListPendingMarkers is the matrix signal's read and the group-closure
// collision check's read. It returns NO ciphertext: what another principal's
// draft may disclose is write-presence and nothing else, and the cheapest way
// to hold that rule is a statement that cannot carry the material.
func (q *Queries) ListPendingMarkers(ctx context.Context, arg ListPendingMarkersParams) ([]ListPendingMarkersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMarkers, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMarkersRow
	for rows.Next() {
		var i ListPendingMarkersRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.KeyID,
			&i.OwnerID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionKeyChanges = `-- name: ListRevisionKeyChanges :many
SELECT org_id, project_id, environment_id, revision, key_id, key_name, change
FROM revision_key_changes
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND revision = ?
ORDER BY key_name
`

type ListRevisionKeyChangesParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	Revision      int64
}

func (q *Queries) ListRevisionKeyChanges(ctx context.Context, arg ListRevisionKeyChangesParams) ([]RevisionKeyChange, error) {
	rows, err := q.db.QueryContext(ctx, listRevisionKeyChanges,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Revision,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionKeyChange
	for rows.Next() {
		var i RevisionKeyChange
		if err := rows.Scan(
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Revision,
			&i.KeyID,
			&i.KeyName,
			&i.Change,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotEntries = `-- name: ListSnapshotEntries :many
SELECT id, org_id, project_id, environment_id, snapshot_id,
       key_id, key_name, classification, ciphertext, value_entry_id
FROM snapshot_entries
WHERE org_id = ? AND project_id = ? AND environment_id = ? AND snapshot_id = ?
ORDER BY key_name
`

type ListSnapshotEntriesParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
	SnapshotID    string
}

func (q *Queries) ListSnapshotEntries(ctx context.Context, arg ListSnapshotEntriesParams) ([]SnapshotEntry, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotEntries,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SnapshotID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotEntry
	for rows.Next() {
		var i SnapshotEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SnapshotID,
			&i.KeyID,
			&i.KeyName,
			&i.Classification,
			&i.Ciphertext,
			&i.ValueEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, org_id, project_id, environment_id, revision, schema_revision, published_by, published_at
FROM snapshots
WHERE org_id = ? AND project_id = ? AND environment_id = ?
ORDER BY revision DESC
`

type ListSnapshotsParams struct {
	OrgID         string
	ProjectID     string
	EnvironmentID string
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, arg.OrgID, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Revision,
			&i.SchemaRevision,
			&i.PublishedBy,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
