// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saml.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const bindSessionToSAMLProvider = `-- name: BindSessionToSAMLProvider :execrows
UPDATE sessions SET saml_provider_id = ?
WHERE id = ? AND provider_id IS NULL AND saml_provider_id IS NULL
`

type BindSessionToSAMLProviderParams struct {
	SamlProviderID sql.NullString
	ID             string
}

// Bind provider provenance before the surrounding session-mint transaction
// commits. The existing OIDC provider column must be empty.
// hikyo:authn-resolution
func (q *Queries) BindSessionToSAMLProvider(ctx context.Context, arg BindSessionToSAMLProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindSessionToSAMLProvider, arg.SamlProviderID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeSAMLTransaction = `-- name: ConsumeSAMLTransaction :execrows
UPDATE saml_transactions SET consumed_at = ?
WHERE id = ? AND consumed_at IS NULL
`

type ConsumeSAMLTransactionParams struct {
	ConsumedAt sql.NullString
	ID         string
}

// hikyo:authn-resolution
func (q *Queries) ConsumeSAMLTransaction(ctx context.Context, arg ConsumeSAMLTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeSAMLTransaction, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredSAMLReplay = `-- name: DeleteExpiredSAMLReplay :execrows
DELETE FROM saml_replay WHERE expires_at <= ?
`

// hikyo:authn-resolution
func (q *Queries) DeleteExpiredSAMLReplay(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSAMLReplay, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRetiringSAMLSPKey = `-- name: DeleteRetiringSAMLSPKey :execrows
DELETE FROM saml_sp_keys WHERE id = ? AND state = 'retiring'
`

// Erasing a retired key deletes both ciphertext and certificate row.
// hikyo:authn-resolution
func (q *Queries) DeleteRetiringSAMLSPKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetiringSAMLSPKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSAMLProvider = `-- name: DeleteSAMLProvider :exec
DELETE FROM saml_providers WHERE id = ?
`

// hikyo:authn-resolution
func (q *Queries) DeleteSAMLProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSAMLProvider, id)
	return err
}

const deleteSessionsForSAMLProvider = `-- name: DeleteSessionsForSAMLProvider :execrows
DELETE FROM sessions WHERE saml_provider_id = ?
`

// hikyo:authn-resolution
func (q *Queries) DeleteSessionsForSAMLProvider(ctx context.Context, samlProviderID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsForSAMLProvider, samlProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveSAMLSPKey = `-- name: GetActiveSAMLSPKey :one
SELECT id, state, encrypted_private_key, certificate_der, fingerprint,
       dek_version, row_version, created_at
FROM saml_sp_keys WHERE state = 'active'
`

// hikyo:authn-resolution
func (q *Queries) GetActiveSAMLSPKey(ctx context.Context) (SamlSpKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveSAMLSPKey)
	var i SamlSpKey
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.EncryptedPrivateKey,
		&i.CertificateDer,
		&i.Fingerprint,
		&i.DekVersion,
		&i.RowVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getSAMLProviderBySlug = `-- name: GetSAMLProviderBySlug :one
SELECT id, slug, display_name, kind, entity_id, acs_url, sso_redirect_url,
       signing_certificates, assurance_policy, allow_email_nameid,
       force_sign_requests, metadata_want_authn_requests_signed, metadata_source, metadata_url, metadata_signed,
       metadata_signing_fingerprint, metadata_valid_until, enabled, row_version,
       created_at, updated_at
FROM saml_providers WHERE slug = ?
`

// hikyo:authn-resolution
func (q *Queries) GetSAMLProviderBySlug(ctx context.Context, slug string) (SamlProvider, error) {
	row := q.db.QueryRowContext(ctx, getSAMLProviderBySlug, slug)
	var i SamlProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.EntityID,
		&i.AcsUrl,
		&i.SsoRedirectUrl,
		&i.SigningCertificates,
		&i.AssurancePolicy,
		&i.AllowEmailNameid,
		&i.ForceSignRequests,
		&i.MetadataWantAuthnRequestsSigned,
		&i.MetadataSource,
		&i.MetadataUrl,
		&i.MetadataSigned,
		&i.MetadataSigningFingerprint,
		&i.MetadataValidUntil,
		&i.Enabled,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSAMLProviderForCallback = `-- name: GetSAMLProviderForCallback :one
SELECT id, slug, display_name, kind, entity_id, acs_url, sso_redirect_url,
       signing_certificates, assurance_policy, allow_email_nameid,
       force_sign_requests, metadata_want_authn_requests_signed, metadata_source, metadata_url, metadata_signed,
       metadata_signing_fingerprint, metadata_valid_until, enabled, row_version,
       created_at, updated_at
FROM saml_providers WHERE id = ?
`

// hikyo:authn-resolution
func (q *Queries) GetSAMLProviderForCallback(ctx context.Context, id string) (SamlProvider, error) {
	row := q.db.QueryRowContext(ctx, getSAMLProviderForCallback, id)
	var i SamlProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.EntityID,
		&i.AcsUrl,
		&i.SsoRedirectUrl,
		&i.SigningCertificates,
		&i.AssurancePolicy,
		&i.AllowEmailNameid,
		&i.ForceSignRequests,
		&i.MetadataWantAuthnRequestsSigned,
		&i.MetadataSource,
		&i.MetadataUrl,
		&i.MetadataSigned,
		&i.MetadataSigningFingerprint,
		&i.MetadataValidUntil,
		&i.Enabled,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSAMLTransactionByRelayState = `-- name: GetSAMLTransactionByRelayState :one
SELECT id, request_id, relay_state_verifier, initiator_verifier, provider_id,
       entity_id, acs_url, purpose, initiating_session_id, account_id,
       environment_id, ceremony_id, credential_epoch,
       created_at, expires_at, consumed_at
FROM saml_transactions WHERE relay_state_verifier = ?
`

// RelayState is the pre-validation lookup key: it resolves the expected
// request/provider before the signed response is parsed and validated once.
// hikyo:authn-resolution
func (q *Queries) GetSAMLTransactionByRelayState(ctx context.Context, relayStateVerifier []byte) (SamlTransaction, error) {
	row := q.db.QueryRowContext(ctx, getSAMLTransactionByRelayState, relayStateVerifier)
	var i SamlTransaction
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RelayStateVerifier,
		&i.InitiatorVerifier,
		&i.ProviderID,
		&i.EntityID,
		&i.AcsUrl,
		&i.Purpose,
		&i.InitiatingSessionID,
		&i.AccountID,
		&i.EnvironmentID,
		&i.CeremonyID,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const guardSAMLProviderForMint = `-- name: GuardSAMLProviderForMint :execrows
UPDATE saml_providers SET row_version = row_version
WHERE id = ? AND row_version = ? AND entity_id = ? AND enabled = 1
`

type GuardSAMLProviderForMintParams struct {
	ID         string
	RowVersion int64
	EntityID   string
}

// hikyo:authn-resolution
func (q *Queries) GuardSAMLProviderForMint(ctx context.Context, arg GuardSAMLProviderForMintParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, guardSAMLProviderForMint, arg.ID, arg.RowVersion, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSAMLProvider = `-- name: InsertSAMLProvider :exec

INSERT INTO saml_providers
    (id, slug, display_name, kind, entity_id, acs_url, sso_redirect_url,
     signing_certificates, assurance_policy, allow_email_nameid,
     force_sign_requests, metadata_want_authn_requests_signed, metadata_source, metadata_url, metadata_signed,
     metadata_signing_fingerprint, metadata_valid_until, enabled, row_version,
     created_at, updated_at)
VALUES (?, ?, ?, 'saml', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
`

type InsertSAMLProviderParams struct {
	ID                              string
	Slug                            string
	DisplayName                     string
	EntityID                        string
	AcsUrl                          string
	SsoRedirectUrl                  string
	SigningCertificates             []byte
	AssurancePolicy                 sql.NullString
	AllowEmailNameid                int64
	ForceSignRequests               int64
	MetadataWantAuthnRequestsSigned int64
	MetadataSource                  string
	MetadataUrl                     sql.NullString
	MetadataSigned                  int64
	MetadataSigningFingerprint      sql.NullString
	MetadataValidUntil              sql.NullString
	Enabled                         int64
	CreatedAt                       string
	UpdatedAt                       string
}

// SAML SP resolution and lifecycle (#72, saml-sp ADR). These rows decide who
// a caller is and how strongly they authenticated, so they live on the same
// proof-free, enumerated authn resolution surface as OIDC.
// hikyo:authn-resolution
func (q *Queries) InsertSAMLProvider(ctx context.Context, arg InsertSAMLProviderParams) error {
	_, err := q.db.ExecContext(ctx, insertSAMLProvider,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.EntityID,
		arg.AcsUrl,
		arg.SsoRedirectUrl,
		arg.SigningCertificates,
		arg.AssurancePolicy,
		arg.AllowEmailNameid,
		arg.ForceSignRequests,
		arg.MetadataWantAuthnRequestsSigned,
		arg.MetadataSource,
		arg.MetadataUrl,
		arg.MetadataSigned,
		arg.MetadataSigningFingerprint,
		arg.MetadataValidUntil,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSAMLReplay = `-- name: InsertSAMLReplay :execrows
INSERT INTO saml_replay (issuer, assertion_id, expires_at, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (issuer, assertion_id) DO NOTHING
`

type InsertSAMLReplayParams struct {
	Issuer      string
	AssertionID string
	ExpiresAt   string
	CreatedAt   string
}

// ON CONFLICT is the atomic replay claim: exactly one concurrent presentation
// inserts, all others observe zero affected rows.
// hikyo:authn-resolution
func (q *Queries) InsertSAMLReplay(ctx context.Context, arg InsertSAMLReplayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSAMLReplay,
		arg.Issuer,
		arg.AssertionID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSAMLSPKey = `-- name: InsertSAMLSPKey :exec
INSERT INTO saml_sp_keys
    (id, state, encrypted_private_key, certificate_der, fingerprint,
     dek_version, row_version, created_at)
VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type InsertSAMLSPKeyParams struct {
	ID                  string
	State               string
	EncryptedPrivateKey []byte
	CertificateDer      []byte
	Fingerprint         string
	DekVersion          int64
	CreatedAt           string
}

// hikyo:authn-resolution
func (q *Queries) InsertSAMLSPKey(ctx context.Context, arg InsertSAMLSPKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertSAMLSPKey,
		arg.ID,
		arg.State,
		arg.EncryptedPrivateKey,
		arg.CertificateDer,
		arg.Fingerprint,
		arg.DekVersion,
		arg.CreatedAt,
	)
	return err
}

const insertSAMLTransaction = `-- name: InsertSAMLTransaction :exec
INSERT INTO saml_transactions
    (id, request_id, relay_state_verifier, initiator_verifier, provider_id,
     entity_id, acs_url, purpose, initiating_session_id, account_id,
     environment_id, ceremony_id, credential_epoch,
     created_at, expires_at, consumed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
`

type InsertSAMLTransactionParams struct {
	ID                  string
	RequestID           string
	RelayStateVerifier  []byte
	InitiatorVerifier   []byte
	ProviderID          string
	EntityID            string
	AcsUrl              string
	Purpose             string
	InitiatingSessionID sql.NullString
	AccountID           sql.NullString
	EnvironmentID       sql.NullString
	CeremonyID          sql.NullString
	CredentialEpoch     int64
	CreatedAt           string
	ExpiresAt           string
}

// hikyo:authn-resolution
func (q *Queries) InsertSAMLTransaction(ctx context.Context, arg InsertSAMLTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertSAMLTransaction,
		arg.ID,
		arg.RequestID,
		arg.RelayStateVerifier,
		arg.InitiatorVerifier,
		arg.ProviderID,
		arg.EntityID,
		arg.AcsUrl,
		arg.Purpose,
		arg.InitiatingSessionID,
		arg.AccountID,
		arg.EnvironmentID,
		arg.CeremonyID,
		arg.CredentialEpoch,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listSAMLProviders = `-- name: ListSAMLProviders :many
SELECT id, slug, display_name, kind, entity_id, acs_url, sso_redirect_url,
       signing_certificates, assurance_policy, allow_email_nameid,
       force_sign_requests, metadata_want_authn_requests_signed, metadata_source, metadata_url, metadata_signed,
       metadata_signing_fingerprint, metadata_valid_until, enabled, row_version,
       created_at, updated_at
FROM saml_providers ORDER BY slug
`

// hikyo:authn-resolution
func (q *Queries) ListSAMLProviders(ctx context.Context) ([]SamlProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSAMLProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlProvider
	for rows.Next() {
		var i SamlProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Kind,
			&i.EntityID,
			&i.AcsUrl,
			&i.SsoRedirectUrl,
			&i.SigningCertificates,
			&i.AssurancePolicy,
			&i.AllowEmailNameid,
			&i.ForceSignRequests,
			&i.MetadataWantAuthnRequestsSigned,
			&i.MetadataSource,
			&i.MetadataUrl,
			&i.MetadataSigned,
			&i.MetadataSigningFingerprint,
			&i.MetadataValidUntil,
			&i.Enabled,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPKeys = `-- name: ListSAMLSPKeys :many
SELECT id, state, encrypted_private_key, certificate_der, fingerprint,
       dek_version, row_version, created_at
FROM saml_sp_keys ORDER BY created_at, id
`

// hikyo:authn-resolution
func (q *Queries) ListSAMLSPKeys(ctx context.Context) ([]SamlSpKey, error) {
	rows, err := q.db.QueryContext(ctx, listSAMLSPKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSpKey
	for rows.Next() {
		var i SamlSpKey
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.EncryptedPrivateKey,
			&i.CertificateDer,
			&i.Fingerprint,
			&i.DekVersion,
			&i.RowVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSAMLProviderForDelete = `-- name: LockSAMLProviderForDelete :one
SELECT id FROM saml_providers WHERE id = ?
`

// SQLite write transactions already serialize; this existence read mirrors
// PostgreSQL's row lock and preserves one cross-engine delete sequence.
// hikyo:authn-resolution
func (q *Queries) LockSAMLProviderForDelete(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockSAMLProviderForDelete, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const markSAMLSPKeyRetiringCAS = `-- name: MarkSAMLSPKeyRetiringCAS :execrows
UPDATE saml_sp_keys
SET state = 'retiring', row_version = row_version + 1
WHERE id = ? AND row_version = ? AND state = 'active'
`

type MarkSAMLSPKeyRetiringCASParams struct {
	ID         string
	RowVersion int64
}

// hikyo:authn-resolution
func (q *Queries) MarkSAMLSPKeyRetiringCAS(ctx context.Context, arg MarkSAMLSPKeyRetiringCASParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSAMLSPKeyRetiringCAS, arg.ID, arg.RowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSAMLProviderCAS = `-- name: UpdateSAMLProviderCAS :execrows
UPDATE saml_providers
SET display_name = ?, acs_url = ?, sso_redirect_url = ?,
    signing_certificates = ?, assurance_policy = ?, allow_email_nameid = ?,
    force_sign_requests = ?, metadata_want_authn_requests_signed = ?, metadata_source = ?, metadata_url = ?,
    metadata_signed = ?, metadata_signing_fingerprint = ?,
    metadata_valid_until = ?, enabled = ?, row_version = row_version + 1,
    updated_at = ?
WHERE id = ? AND row_version = ?
`

type UpdateSAMLProviderCASParams struct {
	DisplayName                     string
	AcsUrl                          string
	SsoRedirectUrl                  string
	SigningCertificates             []byte
	AssurancePolicy                 sql.NullString
	AllowEmailNameid                int64
	ForceSignRequests               int64
	MetadataWantAuthnRequestsSigned int64
	MetadataSource                  string
	MetadataUrl                     sql.NullString
	MetadataSigned                  int64
	MetadataSigningFingerprint      sql.NullString
	MetadataValidUntil              sql.NullString
	Enabled                         int64
	UpdatedAt                       string
	ID                              string
	RowVersion                      int64
}

// entity_id and slug are immutable. Every policy/trust-anchor change bumps the
// version so callback minting can detect reconfiguration and fail closed.
// hikyo:authn-resolution
func (q *Queries) UpdateSAMLProviderCAS(ctx context.Context, arg UpdateSAMLProviderCASParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSAMLProviderCAS,
		arg.DisplayName,
		arg.AcsUrl,
		arg.SsoRedirectUrl,
		arg.SigningCertificates,
		arg.AssurancePolicy,
		arg.AllowEmailNameid,
		arg.ForceSignRequests,
		arg.MetadataWantAuthnRequestsSigned,
		arg.MetadataSource,
		arg.MetadataUrl,
		arg.MetadataSigned,
		arg.MetadataSigningFingerprint,
		arg.MetadataValidUntil,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
