// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanning.sql

package sqlitegen

import (
	"context"
)

const deleteAllScanningDismissals = `-- name: DeleteAllScanningDismissals :execrows
DELETE FROM scanning_dismissals
`

// DeleteAllScanningDismissals drops every dismissal instance-wide: fingerprint
// rotation replaces the scanning key, so every stored fingerprint is now
// unrecomputable and must die (re-fire, the safe direction). Cross-tenant by
// definition: the operator rotation surface, annotated and pinned.
// hikyo:instance-scoped
func (q *Queries) DeleteAllScanningDismissals(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllScanningDismissals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScanningDismissalsForKey = `-- name: DeleteScanningDismissalsForKey :execrows
DELETE FROM scanning_dismissals
WHERE org_id = ? AND project_id = ? AND key_id = ?
`

type DeleteScanningDismissalsForKeyParams struct {
	OrgID     string
	ProjectID string
	KeyID     string
}

// DeleteScanningDismissalsForKey drops one key's dismissals across every
// environment: reclassification to secret makes them moot, and key deletion
// needs them gone before the composite FK will let the key row go.
func (q *Queries) DeleteScanningDismissalsForKey(ctx context.Context, arg DeleteScanningDismissalsForKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanningDismissalsForKey, arg.OrgID, arg.ProjectID, arg.KeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScanningDismissalsForProject = `-- name: DeleteScanningDismissalsForProject :execrows
DELETE FROM scanning_dismissals
WHERE org_id = ? AND project_id = ?
`

type DeleteScanningDismissalsForProjectParams struct {
	OrgID     string
	ProjectID string
}

// DeleteScanningDismissalsForProject removes a project's dismissals: the ADR's
// literal "project deletion removes the project's dismissal rows".
func (q *Queries) DeleteScanningDismissalsForProject(ctx context.Context, arg DeleteScanningDismissalsForProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanningDismissalsForProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScanningDismissal = `-- name: GetScanningDismissal :one
SELECT id FROM scanning_dismissals
WHERE org_id = ? AND project_id = ? AND environment_id = ?
  AND key_id = ? AND rule_digest = ? AND value_fingerprint = ?
`

type GetScanningDismissalParams struct {
	OrgID            string
	ProjectID        string
	EnvironmentID    string
	KeyID            string
	RuleDigest       string
	ValueFingerprint []byte
}

// GetScanningDismissal is the sticky-match lookup: a row for this exact
// (env, key, rule digest, fingerprint) means the value was accepted as-is and
// the warn must not re-fire. The WHERE names the full UNIQUE tuple, so at most
// one row matches: no LIMIT needed, and a nested SELECT EXISTS is rejected by
// the predicate analyzer anyway. Absence is sql.ErrNoRows.
func (q *Queries) GetScanningDismissal(ctx context.Context, arg GetScanningDismissalParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getScanningDismissal,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.KeyID,
		arg.RuleDigest,
		arg.ValueFingerprint,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertScanningDismissal = `-- name: InsertScanningDismissal :exec

INSERT INTO scanning_dismissals (
    id, org_id, project_id, environment_id, key_id, rule_digest, value_fingerprint, created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScanningDismissalParams struct {
	ID               string
	OrgID            string
	ProjectID        string
	EnvironmentID    string
	KeyID            string
	RuleDigest       string
	ValueFingerprint []byte
	CreatedAt        string
	CreatedBy        string
}

// Secret-scanning dismissal rows (#74, secret-scanning ADR section 4). ASCII
// ONLY: sqlc's sqlite path silently mis-slices statements containing non-ASCII.
//
// Tenant-scoped statements bind org_id and project_id from the proof's resolved
// chain, never from caller arguments; environment_id is bound from the proof on
// the environment-addressed statements. The (key identity, rule digest, value
// fingerprint) triple is caller data: the finding's own coordinates.
func (q *Queries) InsertScanningDismissal(ctx context.Context, arg InsertScanningDismissalParams) error {
	_, err := q.db.ExecContext(ctx, insertScanningDismissal,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.KeyID,
		arg.RuleDigest,
		arg.ValueFingerprint,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}
