// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scimauthn.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const deleteSCIMCredentialsForBinding = `-- name: DeleteSCIMCredentialsForBinding :exec
DELETE FROM scim_credentials WHERE org_id = ? AND binding_id = ?
`

type DeleteSCIMCredentialsForBindingParams struct {
	OrgID     string
	BindingID string
}

// hikyo:authn-resolution
func (q *Queries) DeleteSCIMCredentialsForBinding(ctx context.Context, arg DeleteSCIMCredentialsForBindingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSCIMCredentialsForBinding, arg.OrgID, arg.BindingID)
	return err
}

const getSCIMCredential = `-- name: GetSCIMCredential :one
SELECT id, binding_id, principal_id, credential_epoch, created_at, expires_at,
       revoked_at, last_used_at
FROM scim_credentials WHERE org_id = ? AND binding_id = ? AND id = ?
`

type GetSCIMCredentialParams struct {
	OrgID     string
	BindingID string
	ID        string
}

type GetSCIMCredentialRow struct {
	ID              string
	BindingID       string
	PrincipalID     string
	CredentialEpoch int64
	CreatedAt       string
	ExpiresAt       sql.NullString
	RevokedAt       sql.NullString
	LastUsedAt      sql.NullString
}

// hikyo:authn-resolution
func (q *Queries) GetSCIMCredential(ctx context.Context, arg GetSCIMCredentialParams) (GetSCIMCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, getSCIMCredential, arg.OrgID, arg.BindingID, arg.ID)
	var i GetSCIMCredentialRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalID,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSCIMCredentialByVerifier = `-- name: GetSCIMCredentialByVerifier :one
SELECT id, org_id, binding_id, principal_id, verifier, credential_epoch, created_at,
       expires_at, revoked_at, last_used_at
FROM scim_credentials WHERE verifier = ?
`

// Presentation resolves the verifier, never anything inside the value: kind,
// binding, expiry and epoch are read from the row (machine-identities ADR).
// hikyo:authn-resolution
func (q *Queries) GetSCIMCredentialByVerifier(ctx context.Context, verifier []byte) (ScimCredential, error) {
	row := q.db.QueryRowContext(ctx, getSCIMCredentialByVerifier, verifier)
	var i ScimCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BindingID,
		&i.PrincipalID,
		&i.Verifier,
		&i.CredentialEpoch,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertSCIMCredential = `-- name: InsertSCIMCredential :exec

INSERT INTO scim_credentials
    (id, org_id, binding_id, principal_id, verifier, credential_epoch, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSCIMCredentialParams struct {
	ID              string
	OrgID           string
	BindingID       string
	PrincipalID     string
	Verifier        []byte
	CredentialEpoch int64
	CreatedAt       string
	ExpiresAt       sql.NullString
}

// SCIM provisioning, authentication-resolution half (#73).
//
// Two kinds of statement live here and both belong on the enumerated
// resolution surface rather than the proof-carrying repository surface:
//
//  1. `scim_credentials` is what AUTHENTICATES a SCIM wire request. It is
//     resolved before any operation is authorized - there is no proof yet
//     to bind it to, exactly as `sessions` is. Its administration (mint, list,
//     revoke) runs AFTER the ordinary `manage-members(org)` gate, following
//     the OIDC/SAML provider-administration precedent where the operation
//     registry owns the gate and the storage rides here.
//  2. the grant-origin reads the release algorithm needs. `grants` and
//     `grant_origins` are already this surface (authorize() reads them to
//     mint a proof), so a SCIM-side origin release is the same class of
//     write a human revoke is.
//
// Every query is annotated and content-pinned.
// ASCII only: multibyte characters shift sqlite statement offsets.
// hikyo:authn-resolution
func (q *Queries) InsertSCIMCredential(ctx context.Context, arg InsertSCIMCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertSCIMCredential,
		arg.ID,
		arg.OrgID,
		arg.BindingID,
		arg.PrincipalID,
		arg.Verifier,
		arg.CredentialEpoch,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listGrantOriginsForPrincipal = `-- name: ListGrantOriginsForPrincipal :many
SELECT g.id, g.capability, g.org_id, g.project_id, g.env_id, o.kind, o.subject
FROM grants AS g
INNER JOIN grant_origins AS o ON o.grant_id = g.id
WHERE g.principal_id = ?
ORDER BY g.id, o.kind, o.subject
`

type ListGrantOriginsForPrincipalRow struct {
	ID         string
	Capability string
	OrgID      sql.NullString
	ProjectID  sql.NullString
	EnvID      sql.NullString
	Kind       string
	Subject    string
}

// The release algorithm's read: every origin holding every grant row of one
// principal, in one statement. Walking grant rows and then their origins
// one-by-one would be the same information at N+1 queries, and a release
// decision that spans both tables should see them at one instant.
// hikyo:authn-resolution
func (q *Queries) ListGrantOriginsForPrincipal(ctx context.Context, principalID string) ([]ListGrantOriginsForPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantOriginsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantOriginsForPrincipalRow
	for rows.Next() {
		var i ListGrantOriginsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.Kind,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockoutRetentionOrigins = `-- name: ListLockoutRetentionOrigins :many
SELECT g.id, g.principal_id, g.capability, g.org_id, g.project_id, g.env_id, o.subject
FROM grants AS g
INNER JOIN grant_origins AS o ON o.grant_id = g.id
WHERE o.kind = 'lockout-retention'
ORDER BY g.id, o.subject
`

type ListLockoutRetentionOriginsRow struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       sql.NullString
	ProjectID   sql.NullString
	EnvID       sql.NullString
	Subject     string
}

// Every lockout-retention origin in the instance, with the grant row it holds
// (ADR section 2.4). The cure sweep is global rather than per-org because an
// INSTANCE-scope manage-members grant cures every org at once, and a per-org
// sweep would silently leave those retentions standing. Retention origins are
// rare by construction -- one per grant the IdP withdrew from the last member
// manager -- so the whole set is cheap to walk.
// hikyo:authn-resolution
func (q *Queries) ListLockoutRetentionOrigins(ctx context.Context) ([]ListLockoutRetentionOriginsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLockoutRetentionOrigins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLockoutRetentionOriginsRow
	for rows.Next() {
		var i ListLockoutRetentionOriginsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockoutRetentionOriginsInOrg = `-- name: ListLockoutRetentionOriginsInOrg :many
SELECT g.id, g.principal_id, g.capability, g.org_id, g.project_id, g.env_id, o.subject
FROM grants AS g
INNER JOIN grant_origins AS o ON o.grant_id = g.id
WHERE o.kind = 'lockout-retention' AND g.org_id = ?
ORDER BY g.id, o.subject
`

type ListLockoutRetentionOriginsInOrgRow struct {
	ID          string
	PrincipalID string
	Capability  string
	OrgID       sql.NullString
	ProjectID   sql.NullString
	EnvID       sql.NullString
	Subject     string
}

// The cure sweep bounded to ONE org. An org-scope `manage-members` grant cures
// that org and no other, so loading and locking every retention in the instance
// to then discard all but one org's is both tenant-triggerable O(instance) work
// and a cross-tenant timing signal. Only an INSTANCE-scope grant needs the
// unbounded walk above.
// hikyo:authn-resolution
func (q *Queries) ListLockoutRetentionOriginsInOrg(ctx context.Context, orgID sql.NullString) ([]ListLockoutRetentionOriginsInOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listLockoutRetentionOriginsInOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLockoutRetentionOriginsInOrgRow
	for rows.Next() {
		var i ListLockoutRetentionOriginsInOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.Capability,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvID,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMCredentials = `-- name: ListSCIMCredentials :many
SELECT id, binding_id, principal_id, credential_epoch, created_at, expires_at,
       revoked_at, last_used_at
FROM scim_credentials WHERE org_id = ? AND binding_id = ? ORDER BY created_at, id
`

type ListSCIMCredentialsParams struct {
	OrgID     string
	BindingID string
}

type ListSCIMCredentialsRow struct {
	ID              string
	BindingID       string
	PrincipalID     string
	CredentialEpoch int64
	CreatedAt       string
	ExpiresAt       sql.NullString
	RevokedAt       sql.NullString
	LastUsedAt      sql.NullString
}

// hikyo:authn-resolution
func (q *Queries) ListSCIMCredentials(ctx context.Context, arg ListSCIMCredentialsParams) ([]ListSCIMCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMCredentials, arg.OrgID, arg.BindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSCIMCredentialsRow
	for rows.Next() {
		var i ListSCIMCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.PrincipalID,
			&i.CredentialEpoch,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSCIMCredential = `-- name: RevokeSCIMCredential :execrows
UPDATE scim_credentials SET revoked_at = ?
WHERE org_id = ? AND binding_id = ? AND id = ? AND revoked_at IS NULL
`

type RevokeSCIMCredentialParams struct {
	RevokedAt sql.NullString
	OrgID     string
	BindingID string
	ID        string
}

// Revocation bites at the NEXT request: the row is marked, not deleted, so the
// verifier stays occupied and the credential id keeps naming a real thing on
// the administration surface.
// hikyo:authn-resolution
func (q *Queries) RevokeSCIMCredential(ctx context.Context, arg RevokeSCIMCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSCIMCredential,
		arg.RevokedAt,
		arg.OrgID,
		arg.BindingID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSCIMCredentialsForBinding = `-- name: RevokeSCIMCredentialsForBinding :execrows
UPDATE scim_credentials SET revoked_at = ?
WHERE org_id = ? AND binding_id = ? AND revoked_at IS NULL
`

type RevokeSCIMCredentialsForBindingParams struct {
	RevokedAt sql.NullString
	OrgID     string
	BindingID string
}

// Step (1) of the binding-deletion state machine: every credential dies first,
// so no new wire transaction can begin.
// hikyo:authn-resolution
func (q *Queries) RevokeSCIMCredentialsForBinding(ctx context.Context, arg RevokeSCIMCredentialsForBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSCIMCredentialsForBinding, arg.RevokedAt, arg.OrgID, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSCIMCredential = `-- name: TouchSCIMCredential :exec
UPDATE scim_credentials SET last_used_at = ? WHERE id = ?
`

type TouchSCIMCredentialParams struct {
	LastUsedAt sql.NullString
	ID         string
}

// hikyo:authn-resolution
func (q *Queries) TouchSCIMCredential(ctx context.Context, arg TouchSCIMCredentialParams) error {
	_, err := q.db.ExecContext(ctx, touchSCIMCredential, arg.LastUsedAt, arg.ID)
	return err
}
